'use strict';
const ORG = [
{id:'membrane',name:'Cell membrane',job:'Controls what enters and leaves the cell.',hint:'The flexible boundary: a security gate.',both:true},
{id:'cytoplasm',name:'Cytoplasm',job:'The jellylike material inside the cell, around its structures. Many cell reactions happen here.',hint:'The space where the cell’s parts do their work.',both:true},
{id:'nucleus',name:'Nucleus',job:'Holds most of the cell’s DNA. DNA instructions help direct cell activities.',hint:'The instruction center, not the cell’s energy factory.',both:true},
{id:'mitochondria',name:'Mitochondria',job:'Help release usable energy from food through cellular respiration.',hint:'Both plant and animal cells need usable energy.',both:true},
{id:'vacuole',name:'Vacuole',job:'Stores water and other materials. A large central vacuole helps support a plant cell.',hint:'Plants usually have one large central storage space.',both:true},
{id:'wall',name:'Cell wall',job:'A firm layer outside the plant cell membrane that provides support and protection.',hint:'The outer support layer; it does not replace the membrane.',both:false},
{id:'chloroplast',name:'Chloroplast',job:'Uses light energy to make sugars from carbon dioxide and water during photosynthesis.',hint:'Found in many plant cells, especially green leaf cells. Root cells usually lack them.',both:false},
{id:'ribosome',name:'Ribosome',job:'Builds proteins using instructions from the cell.',hint:'A tiny protein builder. Bonus structure: plant and animal cells both have these.',both:true}
];
const LESSONS = [
{title:'What is a cell?',goal:'Explain cell theory and how we study tiny living things.',terms:'cell • cell theory • organism • microscope',activity:'theory',body:`<p>A <strong>cell</strong> is the smallest unit that can carry out the basic processes of life. Some organisms, such as many bacteria, are just one cell. You are made of many cells working together.</p><div class="call"><strong>Cell theory has three big ideas:</strong><ol><li>All living organisms are made of one or more cells.</li><li>The cell is the basic unit of life.</li><li>New cells come from cells that already exist.</li></ol></div><p>Most cells are too small to see clearly with your eyes alone. A <strong>microscope</strong> magnifies them. Start on low power to find a sample; then use higher power to see more detail. Higher power usually shows a smaller area.</p><p>A light microscope’s total magnification equals <strong>eyepiece magnification × objective magnification</strong>. A 10× eyepiece and 4× objective give 40× magnification.</p><div class="ex"><strong>Remember:</strong> A cell has smaller parts, but those parts are not independently living cells. A whole organism can be one cell or many cells.</div>`,practical:`<strong>Try it: scientist’s notebook</strong><ol><li>Draw a dot for one single-celled organism and many dots for a multicellular organism.</li><li>Write the three ideas of cell theory in your own words.</li><li>If you have a microscope, observe a prepared slide with an adult. Draw what you actually see, rather than copying a textbook picture.</li></ol>`},
{title:'The cell’s essential parts',goal:'Connect membrane, cytoplasm, and nucleus to their jobs.',terms:'cell membrane • cytoplasm • nucleus • DNA',activity:'explore',body:`<p>Imagine a busy workshop. It needs a boundary, a working space, and instructions. A typical plant or animal cell has structures that help with each job.</p><ul><li><strong>Cell membrane:</strong> a flexible boundary that controls what moves into and out of the cell.</li><li><strong>Cytoplasm:</strong> the jellylike material inside, around the cell’s structures.</li><li><strong>Nucleus:</strong> contains most of the DNA instructions in plant and animal cells and helps direct activities.</li></ul><p>The workshop comparison is a memory trick. A nucleus does not think like a brain, and the membrane does not make conscious choices.</p><div class="ex"><strong>Important exception:</strong> Bacteria are cells, but they do not have a nucleus. Their DNA is not enclosed in one. Not every kind of cell has every structure in our plant/animal models.</div>`,practical:`<strong>Try it: explain a cell to someone</strong><p>Use a bowl as the membrane, the space inside as cytoplasm, and a folded instruction card as the nucleus. Explain what each represents. The bowl model cannot show a membrane letting some materials through.</p>`},
{title:'How cells get energy',goal:'Tell photosynthesis and cellular respiration apart.',terms:'chloroplast • mitochondria • photosynthesis • cellular respiration',activity:'energy',body:`<p>Cells need energy to grow, repair, and move materials. <strong>Mitochondria</strong> help release usable energy from food during cellular respiration. Typical plant <em>and</em> animal cells have mitochondria.</p><p><strong>Chloroplasts</strong> use light energy to make sugar from water and carbon dioxide during photosynthesis. Many green plant cells have chloroplasts. Animal cells do not. Plant root cells usually do not have chloroplasts.</p><div class="call"><strong>Two different jobs:</strong><br>Photosynthesis: light + water + carbon dioxide → sugar + oxygen.<br>Cellular respiration: sugar + oxygen → carbon dioxide + water + usable energy.<br>These are simplified summaries of complex processes.</div><p>Plants do both! They make sugar in photosynthesis, then release usable energy from food in respiration. They still respire in the dark.</p><div class="ex"><strong>Common mix-up:</strong> Mitochondria release usable energy; they do not create energy from nothing. Chloroplasts make sugar using light energy.</div>`,practical:`<strong>Try it: trace the energy</strong><p>Draw a path from sunlight to a leaf, from the leaf’s sugar to a rabbit that eats it, then to the rabbit’s cells. Mark where chloroplasts and mitochondria do their jobs.</p>`},
{title:'Storage, support & builders',goal:'Explain the jobs of vacuoles, cell walls, and ribosomes.',terms:'vacuole • cell wall • ribosome • protein',activity:'jobs',body:`<p>A <strong>vacuole</strong> stores water and other materials. Many plant cells have a large central vacuole. When it contains plenty of water, it pushes against the cell wall and helps keep the plant firm. Animal cells can have smaller vacuoles.</p><p>The <strong>cell wall</strong> is a firm support layer outside a plant cell’s membrane. Plant cells have <em>both</em> a wall and a membrane. Animal cells have no cell wall.</p><p><strong>Bonus structure: ribosomes</strong> are tiny protein builders. Proteins help cells form structures and carry out many tasks. Plant and animal cells both have ribosomes.</p><div class="ex"><strong>Plant wilt clue:</strong> A plant can wilt when its cells lose water and their vacuoles provide less internal pressure. Its cell walls have not disappeared.</div>`,practical:`<strong>Try it: build a model</strong><p>Use a box for a plant cell wall, a bag inside for its membrane, and a sealed water bottle for its vacuole. Add paper labels for the nucleus, mitochondria, and chloroplasts. Explain each part’s job. This is a model, not a working cell.</p>`},
{title:'Plant cell or animal cell?',goal:'Compare shared structures and key differences.',terms:'plant cell • animal cell • structure • function',activity:'sort',body:`<p>Typical plant and animal cells share a <strong>cell membrane, cytoplasm, nucleus, mitochondria, ribosomes, and vacuoles</strong>. Both need food energy, instructions, and a way to exchange materials.</p><p>Plant cells also have a <strong>cell wall</strong>. Many plant cells, such as green leaf cells, have <strong>chloroplasts</strong> and a large central vacuole. Animal cells have no cell wall or chloroplasts.</p><div class="call"><strong>Don’t memorize the outline alone.</strong> Plant cells often look boxlike because of their walls, but real cells have many shapes. Decide using structures, not just whether a drawing is round or square.</div><p>A diagram is a simplified model. Real structures are not necessarily the same colors or sizes shown here.</p>`,practical:`<strong>Try it: compare and explain</strong><p>Make a three-column chart: plant-only in this comparison, shared, and animal-only. Put mitochondria in “shared.” Explain why a plant needs mitochondria even though it has chloroplasts.</p>`},
{title:'Moving materials & staying balanced',goal:'Predict diffusion and osmosis and explain homeostasis.',terms:'diffusion • osmosis • concentration • homeostasis',activity:'osmosis',body:`<p><strong>Diffusion</strong> is the net movement of particles from a higher concentration to a lower concentration. Think of particles spreading out, like a smell spreading across a room. Particles still move after concentrations become balanced.</p><p><strong>Osmosis</strong> is the net movement of water through a selectively permeable membrane. In our model, water can cross but the dissolved particles cannot. Water tends to move toward the side with <strong>more dissolved particles</strong> (less free water).</p><div class="call">More dissolved particles outside → net water moves out.<br>Fewer dissolved particles outside → net water moves in.<br>Equal concentrations → no net movement; water still moves both ways.</div><p><strong>Homeostasis</strong> means keeping internal conditions within a useful range. Cells exchange nutrients, water, and wastes through their membranes. Body systems help deliver oxygen and food and remove wastes.</p><p>Diffusion and osmosis do not require the cell to spend energy directly. Some other transport processes do.</p>`,practical:`<strong>Try it with an adult: potato water test</strong><ol><li>Have an adult cut two equal potato strips. Keep the starting sizes alike.</li><li>Place one in plain water and the other in salty water for about an hour. Use equal amounts of water.</li><li>Compare firmness before and after. Predict which loses water and record the result. Results depend on salt concentration and time.</li><li>Do not eat the experimental samples. Wash your hands and clean up.</li></ol><p>The water type is what you change; firmness is what you observe. Keep size, time, and temperature alike for a fair comparison.</p>`},
{title:'From tiny parts to a whole organism',goal:'Order levels of organization and connect cells to body systems.',terms:'atom • molecule • tissue • organ • organ system • organism',activity:'order',body:`<p>In multicellular organisms, parts fit into larger levels of organization:</p><div class="call"><strong>Atom → molecule → cell → tissue → organ → organ system → organism</strong></div><ul><li><strong>Atom:</strong> a basic unit of an element.</li><li><strong>Molecule:</strong> atoms bonded together, such as water.</li><li><strong>Cell:</strong> the basic living unit.</li><li><strong>Tissue:</strong> a group of similar cells working together.</li><li><strong>Organ:</strong> different tissues working together, such as a heart.</li><li><strong>Organ system:</strong> organs working together, such as the circulatory system.</li><li><strong>Organism:</strong> the whole living thing.</li></ul><p>The respiratory system brings in oxygen. The circulatory system carries it to cells. The digestive system supplies nutrients; the excretory system removes certain wastes. These systems work together to support homeostasis.</p><div class="ex">An atom or molecule is not a living cell. Single-celled organisms do not have tissues or organs.</div>`,practical:`<strong>Try it: organization chain</strong><p>Write “heart muscle cell,” “heart muscle tissue,” “heart,” “circulatory system,” and “person” on paper cards. Arrange them from simplest to most complex, then explain how each level helps the next.</p>`},
{title:'Growing, dividing & working together',goal:'Explain cell division, specialization, and single-celled life.',terms:'cell division • unicellular • multicellular • specialized',activity:'repair',body:`<p>New cells come from existing cells through <strong>cell division</strong>. In a simple model, a cell copies its DNA before it divides and passes genetic instructions to its new cells.</p><p>In multicellular organisms, division helps with <strong>growth, repair, and replacing worn-out cells</strong>. When you grow, you generally gain more cells; your original cells do not simply stretch to body size.</p><p>A <strong>unicellular</strong> organism has one cell that carries out its life processes. In many single-celled organisms, division makes a new organism.</p><p>A <strong>multicellular</strong> organism has many cells. <strong>Specialized cells</strong> have structures suited to different jobs. A nerve cell carries signals; a muscle cell contracts. Specialized cells depend on other cells and body systems.</p><div class="ex"><strong>Big connection:</strong> Division explains the third idea of cell theory. Cells come from cells, not from nonliving material suddenly turning into a new cell.</div>`,practical:`<strong>Try it: division model</strong><p>Draw one cell with a DNA instruction card inside. Make a copy of the card. Draw the cell dividing so each new cell gets an instruction card. Explain why each new cell needs instructions. This model leaves out the detailed stages of division.</p>`}
];
const BANK = [[],[],[],[],[],[],[],[]];
function Q(topic,text,answer,wrong,why){BANK[topic].push({id:topic+'-'+BANK[topic].length,topic,text,options:[answer,...wrong],correct:0,why});}
// Questions store the correct answer first; the app shuffles answer positions for every attempt.
Q(0,'Which statement belongs to cell theory?','New cells come from existing cells.',['Only animals contain cells.','All cells have a nucleus.','Cells appear from nonliving material.'],'Cell theory says all organisms contain cells, cells are the basic living unit, and cells come from existing cells.');
Q(0,'What is the smallest basic unit of life?','A cell',['An atom','A tissue','An organ'],'Atoms and molecules are smaller, but the cell is the basic living unit.');
Q(0,'A bacterium carries out its life processes in one cell. It is…','Unicellular',['Multicellular','Nonliving because it is small','An organ system'],'Unicellular means one cell. One cell can be an entire organism.');
Q(0,'Why do scientists use microscopes to study most cells?','Most cells are too small to see clearly without magnification.',['Cells are all invisible even with a microscope.','Microscopes turn atoms into cells.','Microscopes make new cells.'],'Magnification helps scientists observe structures too small to see clearly with unaided eyes.');
Q(0,'A 10× eyepiece and a 4× objective give what total magnification?','40×',['14×','6×','400×'],'Multiply the two magnifications: 10 × 4 = 40.');
Q(0,'A 10× eyepiece and a 10× objective give what total magnification?','100×',['20×','10×','1,000×'],'Total magnification is eyepiece × objective: 10 × 10 = 100.');
Q(0,'Which is an example of an organism made of many cells?','A person',['One bacterium','One water molecule','One oxygen atom'],'A person is multicellular. Atoms and molecules are not organisms.');
Q(0,'Why start a microscope observation on low power?','It helps you find the sample in a wider view.',['Low power always shows more detail.','It makes the sample grow.','It copies the sample’s DNA.'],'Low power provides a wider field of view. Find and focus the sample before increasing magnification.');
Q(0,'Which claim is NOT part of cell theory?','Every cell contains chloroplasts.',['Cells are the basic unit of life.','Organisms are made of cells.','Cells come from existing cells.'],'Chloroplasts are in many plant cells, not all cells.');
Q(0,'At higher microscope magnification, the area you can see usually…','Gets smaller.',['Gets larger.','Becomes the entire slide.','Always stays the same.'],'Higher magnification shows greater detail but a smaller field of view.');
Q(1,'Which structure controls what enters and leaves a cell?','Cell membrane',['Nucleus','Mitochondrion','Ribosome'],'The membrane is selectively permeable and regulates movement into and out of the cell.');
Q(1,'Which part holds most DNA in a typical animal cell?','Nucleus',['Vacuole','Cell wall','Cytoplasm only'],'The nucleus contains most of the DNA instructions in typical plant and animal cells.');
Q(1,'What is cytoplasm?','Jellylike material inside the cell, around its structures.',['A hard outer support wall.','A green structure that captures sunlight.','The whole organism.'],'Cytoplasm fills the cell interior around its structures; many reactions take place there.');
Q(1,'The nucleus is compared to an instruction center because it…','Contains DNA that helps direct cell activities.',['Lets water through the outer boundary.','Stores most of a plant’s water.','Makes sugar using sunlight.'],'DNA contains instructions for cell activities. The nucleus is not an energy factory.');
Q(1,'Which would directly disrupt control of materials entering a cell?','Damage to its cell membrane',['Changing the drawing’s color','Removing its diagram labels','Moving the textbook'],'The membrane controls exchange with the surroundings; damage can disrupt this balance.');
Q(1,'Do bacteria have a nucleus?','No; their DNA is not enclosed in a nucleus.',['Yes; every living cell has a nucleus.','No; they have no DNA.','Yes; they have two nuclei.'],'Bacteria are cells with DNA, but lack a membrane-enclosed nucleus.');
Q(1,'Which statement about DNA is best?','It carries genetic instructions.',['It is a cell’s water storage tank.','It is the outer wall of all cells.','It turns sunlight directly into oxygen by itself.'],'DNA carries instructions used by the cell and passed to new cells.');
Q(1,'Which structure is shared by typical plant and animal cells?','Cell membrane',['Cell wall','Chloroplast','Only a large central vacuole'],'Both plant and animal cells have membranes. A plant wall does not replace its membrane.');
Q(1,'Many reactions occur in the material surrounding cell structures. That material is…','Cytoplasm',['The cell wall','The organism','A chloroplast only'],'Cytoplasm is the interior material around the cell’s structures.');
Q(1,'A nucleus is like a “brain” only as a memory trick. What does it really do?','Holds most DNA and helps direct cell activities.',['Thinks and makes decisions.','Pumps blood.','Stores all of the cell’s water.'],'Cell structures do not think. The analogy refers to DNA instructions and control of activities.');
Q(2,'Which structures help release usable energy from food?','Mitochondria',['Chloroplasts only','Cell walls','Vacuoles'],'Mitochondria support cellular respiration, which releases usable energy from food.');
Q(2,'What do chloroplasts do?','Use light energy to make sugars.',['Digest all cell wastes.','Copy the whole organism.','Control everything crossing the membrane.'],'Photosynthesis uses light, carbon dioxide, and water to make sugar; oxygen is released.');
Q(2,'Why do typical plant cells need mitochondria?','They also need to release usable energy from food.',['Plants never use sugar.','Mitochondria give plants cell walls.','Mitochondria replace all chloroplasts.'],'Plants do cellular respiration as well as photosynthesis.');
Q(2,'Which process makes sugar using light energy?','Photosynthesis',['Cellular respiration','Osmosis','Cell division'],'Photosynthesis captures light energy in sugars. Respiration releases usable energy from food.');
Q(2,'Which process releases usable energy from sugar?','Cellular respiration',['Photosynthesis','Osmosis','Magnification'],'Cells use respiration to release usable energy from food.');
Q(2,'Which are inputs to photosynthesis in our simple summary?','Light, water, and carbon dioxide',['Sugar and oxygen only','DNA and salt','Protein and cell walls'],'Chloroplasts use light, water, and carbon dioxide to produce sugars and oxygen.');
Q(2,'Which is a product of photosynthesis?','Sugar',['A nucleus','A new cell wall in every animal','Salt'],'Photosynthesis makes sugar and releases oxygen.');
Q(2,'Do animal cells normally have chloroplasts?','No.',['Yes, in every animal cell.','Only when an animal eats a leaf.','Only during cell division.'],'Animals get food by eating or absorbing it; they do not normally have chloroplasts.');
Q(2,'What can a plant still do in the dark?','Cellular respiration',['Photosynthesis without light','Create sunlight','Stop needing energy forever'],'Plants still release usable energy from food by respiration in the dark.');
Q(2,'Which plant cells usually lack chloroplasts?','Cells in roots underground',['Green leaf cells','All plant cells','Only cells with mitochondria'],'Root cells usually do not receive light and usually lack chloroplasts. Many green leaf cells have them.');
Q(3,'Which structure stores water and other materials?','Vacuole',['Ribosome','Cell wall','Mitochondrion'],'Vacuoles store materials; a large central vacuole is typical of many plant cells.');
Q(3,'Where is the plant cell wall?','Outside the cell membrane',['Inside the nucleus','Inside a mitochondrion','Only in animal cells'],'The cell wall supports and protects the plant cell outside its membrane.');
Q(3,'A plant is losing water and wilting. Which structure has lost some stored water?','Its large central vacuole',['Its ribosomes','Its DNA','Its chloroplasts only'],'Less water in vacuoles means less pressure against cell walls, reducing firmness.');
Q(3,'Which structure builds proteins?','Ribosome',['Cell wall','Vacuole','Chloroplast'],'Ribosomes make proteins. This is a bonus structure beyond the main seven in the Florida organelle benchmark.');
Q(3,'Does a plant cell wall replace its membrane?','No; a plant cell has both.',['Yes; the wall does every membrane job.','Only in green leaves.','Plants have neither.'],'The wall provides support outside a membrane that regulates materials crossing the boundary.');
Q(3,'Which helps a plant cell stay firm when filled with water?','A large central vacuole',['A ribosome','An empty nucleus','Only a microscope'],'Water in the central vacuole creates internal pressure against the cell wall.');
Q(3,'Which is a support structure found in plant but not animal cells?','Cell wall',['Cell membrane','Nucleus','Mitochondrion'],'Plant cell walls provide support; animal cells do not have cell walls.');
Q(3,'Which is true about typical animal cell vacuoles?','They may be smaller than a plant’s large central vacuole.',['Animals always have one huge central vacuole.','They make all the cell’s proteins.','They replace the cell membrane.'],'Animal cells can have smaller vacuoles, while many plant cells have a large central one.');
Q(3,'Which pair correctly matches a structure to a job?','Ribosome — builds proteins',['Vacuole — captures sunlight','Cell wall — holds most DNA','Nucleus — provides a hard outer wall'],'Ribosomes build proteins; vacuoles store materials and cell walls provide support.');
Q(3,'If a cell’s protein builders stop working, which structures are affected?','Ribosomes',['Vacuoles','Cell walls','Chloroplasts only'],'Ribosomes are the sites where proteins are built.');
Q(4,'Which pair is found in typical plant AND animal cells?','Nucleus and mitochondria',['Cell wall and chloroplasts','Chloroplasts and mitochondria','Cell wall and nucleus'],'Both types have a nucleus and mitochondria; animals lack cell walls and chloroplasts.');
Q(4,'A cell has a wall and chloroplasts. In our plant/animal comparison, it is most likely…','A plant cell',['An animal cell','A tissue rather than a cell','A nonliving atom'],'Cell walls and chloroplasts identify a typical green plant cell in this comparison.');
Q(4,'Which feature is NOT typical of an animal cell?','A cell wall',['A membrane','Cytoplasm','Mitochondria'],'Animal cells have a membrane but no cell wall.');
Q(4,'Why should you avoid identifying a cell only by its outline?','Real cells have many shapes; structures give better evidence.',['All round cells are plants.','All square cells are animals.','Cells have no structures.'],'Textbook shapes are simplified. Look at structures such as a wall or chloroplasts.');
Q(4,'Which statement is correct?','Plant and animal cells both use energy.',['Only animal cells respire.','Plants do not need mitochondria.','All plant cells have chloroplasts.'],'Both types release usable energy from food; plants also do photosynthesis in suitable cells.');
Q(4,'Which structure is shared by typical plant and animal cells?','Cytoplasm',['Cell wall','Chloroplast','Only a large central vacuole'],'Both types have cytoplasm around their cell structures.');
Q(4,'A green leaf cell often has a large central vacuole. What is its main role?','Storage and helping support the cell',['Building proteins','Holding all DNA','Replacing the membrane'],'A large central vacuole stores water and other materials and supports firmness.');
Q(4,'Which structure belongs in the “shared by both” column?','Ribosome',['Cell wall','Chloroplast','Only the outer support wall'],'Both plant and animal cells build proteins using ribosomes.');
Q(4,'A root cell lacks chloroplasts. Can it still be a plant cell?','Yes; not all plant cells have chloroplasts.',['No; it must be an animal.','No; it is not alive.','Only if it lacks a membrane.'],'Plant cells in roots usually lack chloroplasts. The cell wall and other features still fit a plant cell.');
Q(4,'Which outer structures does a typical plant cell have?','Cell wall and cell membrane',['Cell wall only','Membrane only, never a wall','Neither a wall nor a membrane'],'A plant cell has a supporting wall outside its membrane.');
Q(5,'During diffusion, net movement is usually…','From higher to lower concentration',['From lower to higher concentration','Only into cells, never out','Only when the nucleus pushes particles'],'Diffusion is net movement down a concentration gradient. Particles continue moving at balance.');
Q(5,'Osmosis is the movement of…','Water across a selectively permeable membrane',['DNA through a microscope','Cells into a new tissue','Proteins built on ribosomes'],'Osmosis is diffusion of water across a selectively permeable membrane.');
Q(5,'In our model, dissolved particles cannot cross. There are more outside than inside. Net water movement is…','Out of the cell',['Into the cell','Always zero','Toward the nucleus only'],'Water tends to move toward the side with more dissolved particles, so it moves out.');
Q(5,'In our model, dissolved particles cannot cross. There are fewer outside than inside. Net water movement is…','Into the cell',['Out of the cell','Always zero','Only into the cell wall'],'Water tends to move toward the higher dissolved-particle concentration inside.');
Q(5,'Equal dissolved-particle concentrations are on both sides. Water…','Moves both ways with no net movement',['Stops moving completely','Moves only inward','Moves only outward'],'At balance, water still moves in both directions; the net amounts balance.');
Q(5,'What is homeostasis?','Maintaining internal conditions within a useful range',['Making all conditions identical forever','Making every cell the same shape','Only growing taller'],'Cells and organisms maintain internal balance within ranges, not perfectly unchanging conditions.');
Q(5,'Which change makes a potato comparison unfair?','Using different-sized strips for the two water types',['Using equal soaking times','Using equal water amounts','Recording the starting firmness'],'Different strip sizes introduce another variable, making the water-type comparison harder to interpret.');
Q(5,'Which system brings oxygen into the body?','Respiratory system',['Digestive system','Excretory system','Reproductive system'],'The respiratory system brings in oxygen; the circulatory system carries it to cells.');
Q(5,'Which processes do not require the cell to spend energy directly?','Diffusion and osmosis',['Every kind of transport','Protein building and DNA copying','Cell division and growth'],'Diffusion and osmosis are passive; some other kinds of transport require cellular energy.');
Q(5,'A smell spreads across a room. Which idea does that illustrate?','Diffusion',['Cell division','Photosynthesis','Specialization'],'Particles spread from a higher concentration toward lower concentrations through random motion.');
Q(6,'Which order runs from smallest level to largest?','Cell → tissue → organ → organ system → organism',['Organ → cell → tissue → organism → system','Tissue → cell → organ → organism → system','Organism → system → organ → tissue → cell'],'Cells work together in tissues, tissues in organs, organs in systems, and systems in organisms.');
Q(6,'A heart is an example of…','An organ',['One cell','An atom','An entire organism'],'A heart consists of different tissues working together.');
Q(6,'Similar cells working together form…','A tissue',['An atom','A whole organ system automatically','A molecule'],'A tissue is a group of similar cells performing a related function.');
Q(6,'The circulatory system is an example of…','An organ system',['One organ','One molecule','One cell'],'The heart and blood vessels work together as an organ system.');
Q(6,'A whole living person is an example of…','An organism',['One tissue','One organ','One atom'],'An organism is an individual living thing.');
Q(6,'What comes directly before cells in this organization chain?','Molecules',['Organ systems','Organs','Tissues'],'The chain is atoms, molecules, cells, tissues, organs, organ systems, organisms.');
Q(6,'Which two systems work together to deliver oxygen to cells?','Respiratory and circulatory',['Digestive and reproductive','Nervous and reproductive','Excretory and digestive only'],'The respiratory system brings in oxygen; the circulatory system transports it.');
Q(6,'Do single-celled organisms have tissues and organs?','No; one cell carries out their life processes.',['Yes; all organisms have hearts.','Yes; each molecule is an organ.','Only when using a microscope.'],'Tissues and organs are levels found in multicellular organisms, not single-celled ones.');
Q(6,'Which level consists of atoms bonded together?','Molecule',['Tissue','Organ','Organism'],'A molecule is made of bonded atoms, such as water.');
Q(6,'Which pair matches the correct levels?','Heart muscle tissue → heart organ',['Heart organ → one oxygen atom','Person tissue → heart organism','Cell organ system → heart molecule'],'Muscle tissue is part of the heart, and the heart is an organ in the circulatory system.');
Q(7,'How are new cells formed?','Through division of existing cells',['From empty air appearing alive','By an organ turning into an atom','Only from sunlight'],'New cells arise from cells that already exist, as stated in cell theory.');
Q(7,'Why does a cell copy its DNA before dividing in our simple model?','Each new cell needs genetic instructions.',['To make the microscope brighter','To remove every membrane','To turn into a molecule'],'Copying DNA allows genetic instructions to pass to new cells.');
Q(7,'Cell division in your body helps with…','Growth and repair',['Making sunlight','Removing every tissue','Turning animal cells into plant cells'],'Division makes more cells for growth, repair, and replacement.');
Q(7,'An organism made of one cell is…','Unicellular',['Multicellular','An organ','A tissue'],'Uni means one; multi means many.');
Q(7,'Why do specialized cells have different structures?','Their structures help them carry out different jobs.',['Only one kind of cell needs energy.','Different cells have no membranes.','Cells can choose to become atoms.'],'Structure relates to function: muscle cells contract and nerve cells carry signals.');
Q(7,'Which is an example of a specialized cell’s function?','A nerve cell carries signals.',['A water molecule pumps blood.','An atom makes a tissue by itself.','A cell wall sends thoughts.'],'Nerve cells are adapted to transmit signals; muscle cells are adapted to contract.');
Q(7,'For many single-celled organisms, division can…','Produce another organism',['Produce a heart','Make an organ system','Stop all life processes permanently'],'When the whole organism is one cell, cell division can be reproduction.');
Q(7,'As a child grows, what generally happens?','The body gains more cells through division.',['The original cells stretch to body size.','Every cell becomes a chloroplast.','The body loses all its tissues.'],'Growth generally involves increasing cell number, along with changes in cell size and tissues.');
Q(7,'Which cell theory idea is supported by cell division?','Cells come from pre-existing cells.',['Every organism has a cell wall.','Only plants have cells.','Cells come from nonliving rocks.'],'A cell dividing into new cells demonstrates that new cells come from existing cells.');
Q(7,'Why do cells in a multicellular organism depend on one another?','Different cells and systems perform jobs that support the whole organism.',['Every cell performs exactly the same job.','Only one cell ever uses food.','Cells do not need materials.'],'Specialized cells share work; systems supply nutrients, oxygen, and waste removal.');
const FAQ = [
['What is a cell?','A cell is the smallest basic unit of life. Some living things are one cell; your body has many. Think of a living building block, not a brick that is itself nonliving.'],
['How can I remember the organelles?', 'Membrane = gate; nucleus = instruction center; cytoplasm = working space; mitochondria = release energy from food; chloroplasts = make sugar using light; vacuole = storage; wall = support. These comparisons are memory aids.'],
['Do plants have mitochondria?', 'Yes! Typical plant and animal cells have mitochondria. Plants make sugar using chloroplasts, then use cellular respiration to release usable energy from food. Plants also respire in the dark.'],
['Cell wall or cell membrane?', 'A plant cell has both. The wall is the firm outside support layer. The membrane is the flexible boundary inside the wall that controls what crosses. Animal cells have a membrane but no wall.'],
['Which way does water move?', 'In our osmosis model, only water can cross. Water moves net toward the side with more dissolved particles. More outside: water moves out. Fewer outside: water moves in. Equal: no net movement, but water still moves both ways.'],
['What are the levels of organization?', 'Atom → molecule → cell → tissue → organ → organ system → organism. Try: heart muscle cell → heart muscle tissue → heart → circulatory system → person.'],
['What if I get an answer wrong?', 'Read the explanation, return to that lesson, and try the practice game. You can retry quizzes with different questions. Your highest quiz score stays saved. Mistakes do not erase a mastered lesson.'],
['What should I study for my test?', 'Start with your teacher’s study guide. In this app, review cell theory, the seven major structures, plant/animal differences, life processes, and levels of organization. Then use study cards and the final challenge.'],
['Is every cell the same?', 'No. Plant, animal, and bacterial cells differ. Bacteria lack a nucleus. Even within your body, specialized cells have shapes and structures that help them perform different jobs.']
];
function L(title,goal,terms,body,practical,activity='scenario'){const i=LESSONS.length;LESSONS.push({title,goal,terms,body,practical,activity});BANK.push([]);return i;}
L('Design a fair investigation','Identify variables and collect useful evidence.','independent • dependent • controlled variable • hypothesis',`<p>Scientists ask questions, use evidence, and revise explanations. Inquiry is not always one fixed list of steps. An experiment tests an idea by changing a factor and measuring a result.</p><ul><li><strong>Independent variable:</strong> the factor you intentionally change.</li><li><strong>Dependent variable:</strong> the result you measure.</li><li><strong>Controlled variables:</strong> factors you keep alike for a fair comparison.</li></ul><div class="call">Does ramp height change how far a toy car rolls? Change the height, measure the distance, and keep the car, surface, and release method alike.</div><p>A hypothesis is a testable proposed explanation. Evidence may support it or lead you to revise it. A good experiment does not have to produce the result you expected.</p>`,`<strong>Try it: toy-car inquiry</strong><p>Use a toy car and a low book ramp on the floor. Change only ramp height. Measure travel distance three times at each height. Record all results; don’t push the car. Keep the path clear.</p>`,'variables');
L('Observations, inferences & reliable results','Separate measurements from explanations and improve reliability.','observation • inference • repetition • replication',`<p>An <strong>observation</strong> uses senses or instruments: “The strip is 5 cm long.” An <strong>inference</strong> is an explanation based on observations: “The strip may have absorbed water.” An inference can be reasonable and still need more evidence.</p><div class="call"><strong>Repetition:</strong> you repeat trials in your own investigation.<br><strong>Replication:</strong> other investigators repeat your methods to check results.</div><p>Multiple trials reveal variation. Share detailed methods so another scientist can test your findings. Compare patterns and look for unusual data; do not erase a result simply because it disagrees with your guess.</p>`,`<strong>Try it: data detective</strong><p>Drop the same paper spinner from the same safe height three times and time each fall. Write one observation and one inference. Give your instructions to a family member to replicate the test. Stay on the floor.</p>`);
L('Scientific theories, laws & models','Distinguish explanations, patterns, and representations.','scientific theory • scientific law • model • evidence',`<p>A <strong>scientific theory</strong> is a broad explanation supported by extensive evidence. Cell theory explains how life is organized. A theory is not merely a wild guess.</p><p>A <strong>scientific law</strong> describes a consistent relationship or pattern, often mathematically. Laws describe; theories explain. <strong>A theory does not turn into a law</strong> when enough evidence arrives.</p><p>A <strong>model</strong> represents something that may be too large, small, slow, or complex to study directly. Models help make predictions, but all leave out details. Scientists revise ideas when new evidence shows a better explanation.</p>`,`<strong>Try it: model limits</strong><p>Use a globe, map, or cell drawing. Name two things it shows well and two things it leaves out. Explain why scientists still use imperfect models.</p>`);
L('Forces & motion','Predict the effect of balanced and unbalanced forces.','contact force • gravity • magnetism • net force',`<p>A <strong>force</strong> is a push or pull. Friction and a hand pushing a cart are contact forces. Gravity and magnetism can act at a distance.</p><p><strong>Balanced forces</strong> have a net force of zero: they do not change an object’s velocity. The object can be at rest <em>or moving at constant speed in a straight line</em>.</p><p><strong>Unbalanced forces</strong> can change speed or direction. For opposite forces, subtract the smaller from the larger. For forces in the same direction, add them.</p><div class="call">A 10 N push right and 4 N push left give a net force of 6 N right. A moving cart with balanced forces does not automatically stop.</div><p>Friction resists sliding between surfaces. Gravity pulls objects with mass toward one another.</p>`,`<strong>Try it: friction comparison</strong><p>Slide a toy gently across a smooth surface and then a towel. Keep the starting motion as similar as possible and compare how far it moves. Explain the role of friction.</p>`,'forces');
L('Speed & motion graphs','Calculate speed and interpret distance-time and position-time graphs.','speed • distance • time • slope • position',`<p><strong>Average speed = total distance ÷ total time.</strong> Traveling 20 meters in 5 seconds gives 4 meters per second (m/s). Always include units.</p><p>On a <strong>distance-traveled vs. time graph</strong>, time is horizontal and accumulated distance is vertical. A flat section means stopped. A steeper upward slope means a faster speed. A straight sloping line means constant speed.</p><div class="call">Accumulated distance does not decrease. This graph alone does not tell you direction. On a <strong>position vs. time graph</strong>, position can increase or decrease; a change in slope’s sign can show reversal of direction.</div><p>Use the change between two points: speed = change in distance ÷ change in time. A line going from 0 m at 0 s to 12 m at 3 s represents 4 m/s.</p>`,`<strong>Try it: measure your speed</strong><p>Mark a short safe walking route, measure its distance, and time your walk. Divide meters by seconds. Repeat three times and compare results. Walk; don’t run near traffic or stairs.</p>`,'graphs');
L('Energy transfer & transformation','Trace potential and kinetic energy and conservation.','kinetic • potential • transformation • conservation',`<p><strong>Kinetic energy</strong> is energy of motion. <strong>Potential energy</strong> is stored energy associated with position or arrangement. A raised toy has gravitational potential energy; a stretched rubber band has elastic potential energy.</p><p>As an object falls, gravitational potential energy decreases and kinetic energy increases. Energy can transfer between objects and transform between forms.</p><div class="call"><strong>Conservation of energy:</strong> energy cannot be created or destroyed; it can change form or move between objects.</div><p>A battery stores chemical energy. In a flashlight, it becomes electrical energy, light, and thermal energy. Energy that spreads as heat is not destroyed. A model without friction is an idealization; real systems often warm their surroundings.</p>`,`<strong>Try it: energy chain</strong><p>Draw battery → flashlight → light + warmth. Name the energy forms at each stage. Then trace a ball rolling down a low ramp into a soft barrier.</p>`,'energySlider');
L('Earth’s interacting spheres','Connect the geosphere, hydrosphere, atmosphere, and biosphere.','geosphere • hydrosphere • atmosphere • biosphere',`<p>Earth’s systems interact:</p><ul><li><strong>Geosphere:</strong> rocks, soil, and Earth’s solid parts.</li><li><strong>Hydrosphere:</strong> water, including oceans, rivers, groundwater, and ice.</li><li><strong>Atmosphere:</strong> the surrounding gases.</li><li><strong>Biosphere:</strong> living organisms.</li></ul><div class="call">Rain soaking into soil connects atmosphere, hydrosphere, and geosphere. A tree taking up that water adds the biosphere.</div><p>A single event can involve several spheres. The categories help scientists study connections, not separate worlds.</p>`,`<strong>Try it: sphere hunt</strong><p>Look outside and find one example of each sphere. Draw connections between at least three: for example, rain → soil → plant. Do not collect unknown plants or animals.</p>`);
L('Atmosphere: layers & protection','Identify major layers and what the atmosphere does.','troposphere • stratosphere • ozone • nitrogen',`<p>Earth’s atmosphere is mostly <strong>nitrogen (about 78%)</strong> and <strong>oxygen (about 21%)</strong>, with small amounts of other gases and varying water vapor.</p><p>From the ground upward: <strong>troposphere, stratosphere, mesosphere, thermosphere, exosphere</strong>. Most weather happens in the troposphere. The stratosphere contains the main ozone layer, which absorbs much of the Sun’s harmful ultraviolet radiation.</p><div class="call">Air pressure generally decreases as altitude increases. Atmospheric temperature does not simply decrease through every layer.</div><p>The atmosphere provides gases needed by living things, influences temperature, and helps protect Earth. Greenhouse gases absorb and emit infrared radiation, helping keep the planet warm enough for life.</p>`,`<strong>Try it: layer ladder</strong><p>Draw a five-rung ladder with the atmosphere’s layers in order. Put a cloud near the troposphere and the ozone layer in the stratosphere. Mark decreasing pressure as you move upward.</p>`);
L('Conduction, convection & radiation','Identify how thermal energy moves in real situations.','conduction • convection • radiation • temperature',`<p>Thermal energy transfers from warmer regions to cooler regions.</p><ul><li><strong>Conduction:</strong> transfer by direct contact, such as warm sand touching your feet.</li><li><strong>Convection:</strong> transfer by movement of liquids or gases. Warmer, less-dense fluid often rises; cooler, denser fluid sinks.</li><li><strong>Radiation:</strong> energy carried by electromagnetic waves, such as sunlight warming sand. It does not need matter to travel through.</li></ul><div class="call">Beach chain: Sun → sand by radiation; sand → feet by conduction; circulating warm and cool air by convection.</div><p>More than one process can happen at the same time. Identify the specific part of the situation being described.</p>`,`<strong>Try it: heat detective</strong><p>Find a sunlight example, a contact example, and an air-movement example around your home. Draw arrows for energy movement. Observe only; do not touch hot objects or use a stove.</p>`,'heat');
L('Water cycle: follow a drop','Trace changes of state and movement through the water cycle.','evaporation • condensation • precipitation • transpiration',`<p>The <strong>Sun</strong> supplies energy for much evaporation; <strong>gravity</strong> drives falling precipitation and downhill flow.</p><ul><li><strong>Evaporation:</strong> liquid water becomes water vapor.</li><li><strong>Condensation:</strong> vapor becomes liquid droplets.</li><li><strong>Precipitation:</strong> water falls as rain, snow, sleet, or hail.</li><li><strong>Transpiration:</strong> water vapor leaves plants, mainly through leaves.</li><li><strong>Runoff:</strong> water flows over land.</li><li><strong>Infiltration:</strong> water enters soil; some moves as groundwater.</li></ul><div class="call">A water drop does not follow one mandatory circular route. It can stay in an ocean, plant, glacier, or underground for very different lengths of time.</div><p>Clouds are tiny liquid droplets or ice crystals, not just invisible water vapor.</p>`,`<strong>Try it: mini water cycle</strong><p>With an adult, seal a little water in a clear bag and tape it securely to a window. Mark the starting water level. Observe droplets over time and explain evaporation and condensation. Keep the bag away from young children.</p>`,'water');
L('Weather, climate & global patterns','Explain winds, ocean currents, and short- versus long-term patterns.','weather • climate • wind • current • jet stream',`<p><strong>Weather</strong> is the short-term state of the atmosphere. <strong>Climate</strong> describes long-term patterns, usually over decades. One storm does not define a region’s climate.</p><p>The Sun heats Earth unevenly. Differences in temperature and pressure help drive winds. Earth’s rotation changes the direction of large-scale air and ocean movement. Ocean currents redistribute energy; winds can drive surface currents.</p><div class="call">A sea breeze often blows toward land during the day: land warms faster, warm air over land rises, and cooler ocean air moves in near the surface.</div><p><strong>Jet streams</strong> are fast-moving winds high in the atmosphere that help steer weather. Scientists use temperature, pressure, wind, humidity, and precipitation measurements to describe and predict weather.</p>`,`<strong>Try it: weather journal</strong><p>Record the temperature, cloud cover, and rainfall for five days using a trusted weather report or safe observation. Describe that week’s weather. Explain why five days do not establish the climate.</p>`);
L('Weathering, erosion & deposition','Separate breaking down, carrying away, and settling.','physical weathering • chemical weathering • erosion • deposition',`<p><strong>Weathering</strong> breaks down rock where it is. Physical weathering changes size or shape without changing the material’s chemistry, such as water freezing in cracks. Chemical weathering changes minerals, such as acids reacting with limestone.</p><p><strong>Erosion</strong> moves material by water, wind, ice, or gravity. <strong>Deposition</strong> happens when carried material settles.</p><div class="call">Break → move → settle. A river can weather rock, erode loose sediment, then deposit it where the flow slows.</div><p>Plant roots can widen cracks. Chemical changes and physical breakup often work together.</p>`,`<strong>Try it: sediment model</strong><p>With an adult, put a little clean sand and water in a clear jar. Close the lid, swirl gently, and let it rest. Observe transport during swirling and deposition as particles settle. Keep sand out of sinks and drains.</p>`,'earth');
L('Landforms & surface changes','Connect landforms to water, wind, ice, and gravity.','delta • dune • canyon • glacier • sediment',`<p>Landforms develop through many processes over long times. Rivers can cut valleys and canyons by erosion. A <strong>delta</strong> can form where a river enters slower-moving water and deposits sediment.</p><p>Wind can transport sand and deposit it as <strong>dunes</strong>. Moving glaciers erode and deposit material. Gravity can move rock and soil downhill in landslides.</p><div class="call">When a transporting agent slows, it often loses the ability to carry as much sediment. Larger particles tend to settle before smaller ones.</div><p>Topographic maps use contour lines to connect equal elevations. Closely spaced contour lines show a steeper slope; widely spaced lines show a gentler one.</p>`,`<strong>Try it: landscape sketch</strong><p>Draw a river entering a lake. Show where it is likely to deposit sediment as it slows. Add a dune formed by wind and label each process.</p>`);
L('Classification: sorting living things','Use shared characteristics, domains, and nested groups.','domain • kingdom • genus • species • classification',`<p>Scientists classify organisms using shared traits and evidence of relationships. The broadest group in the three-domain system is <strong>domain</strong>: Bacteria, Archaea, and Eukarya.</p><p>Bacteria and Archaea have cells without nuclei. Eukarya includes organisms with cells that have nuclei, such as animals, plants, fungi, and many protists.</p><div class="call">Broad to specific: <strong>Domain → Kingdom → Phylum → Class → Order → Family → Genus → Species</strong>.</div><p>Scientific names use two parts: genus and species. In <em>Homo sapiens</em>, Homo is the genus. Organisms in the same genus are in a more specific shared group than organisms sharing only a kingdom.</p><p>Use several characteristics to identify an organism. A simple branching key asks a series of trait-based questions.</p>`,`<strong>Try it: sorting key</strong><p>Make a key for four familiar animals using yes/no questions, such as “has feathers?” or “has a shell?” Use observable traits, not “looks nice.” Do not handle wild organisms.</p>`,'classification');
L('Body systems: supply, transport & waste','Explain how systems deliver materials to cells and remove wastes.','digestive • respiratory • circulatory • excretory • reproductive',`<ul><li><strong>Digestive:</strong> breaks food down and absorbs nutrients.</li><li><strong>Respiratory:</strong> exchanges oxygen and carbon dioxide with the environment.</li><li><strong>Circulatory:</strong> transports blood, oxygen, nutrients, and wastes.</li><li><strong>Excretory:</strong> removes metabolic wastes and helps regulate water balance; kidneys filter blood and produce urine.</li><li><strong>Reproductive:</strong> produces reproductive cells and enables production of offspring.</li></ul><div class="call">When you exercise, muscle cells need more oxygen and usable energy. Breathing and heart rate increase to help supply materials and transport wastes.</div><p>The digestive tract removes undigested food; the kidneys remove dissolved metabolic wastes from blood. These are related but different jobs.</p>`,`<strong>Try it: delivery map</strong><p>Draw lungs → blood → muscle cells for oxygen, and digestive tract → blood → cells for nutrients. Add arrows showing wastes leaving cells and traveling to removal systems.</p>`,'systems');
L('Body systems: movement, control & defense','Connect body systems to protection, signals, and movement.','nervous • skeletal • muscular • immune • integumentary',`<ul><li><strong>Nervous:</strong> senses conditions and coordinates responses using signals.</li><li><strong>Skeletal:</strong> supports the body and protects organs.</li><li><strong>Muscular:</strong> contracts to produce movement with the skeleton.</li><li><strong>Immune:</strong> helps defend against infectious agents.</li><li><strong>Integumentary:</strong> skin, hair, and nails; protection and temperature regulation.</li></ul><div class="call">Touch something unexpectedly warm: sensory nerves detect it, the nervous system coordinates a response, and muscles can move your hand away. Do not test this with hot objects.</div><p>Systems interact to support homeostasis. Sweat evaporating can cool skin; blood flow helps move thermal energy. Skin is also a barrier against many pathogens.</p>`,`<strong>Try it: safe response model</strong><p>Have someone say “go,” then gently raise your hand. Trace the signal from hearing the word to your brain, nerves, and muscles. Explain how bones and muscles work together.</p>`,'systems');
L('Infectious agents & staying healthy','Distinguish bacteria, viruses, fungi, and parasites.','virus • bacterium • fungus • parasite • pathogen',`<p>A <strong>pathogen</strong> is an infectious agent that can cause disease. Not all microorganisms cause illness; many are useful.</p><ul><li><strong>Bacteria:</strong> single-celled organisms without nuclei. Some cause disease; many do not.</li><li><strong>Viruses:</strong> not cells; they must use a host cell to make more virus particles.</li><li><strong>Fungi:</strong> organisms with nuclei, including yeasts and molds. Some can cause infections.</li><li><strong>Parasites:</strong> organisms that live on or in a host and benefit at its expense; some are single-celled and others multicellular.</li></ul><div class="call">Antibiotics act against certain bacterial infections, not viruses. Medicines should be used only with a responsible adult and a healthcare professional’s guidance.</div><p>Handwashing, appropriate vaccines, covering coughs, and avoiding sharing personal items can reduce spread. The immune system provides defenses. You cannot identify the cause of an illness from one symptom alone.</p>`,`<strong>Try it: transmission model</strong><p>Use paper tokens as imaginary microbes and trace how touching shared objects could transfer them. Then explain how handwashing breaks a transfer path. This paper model leaves out many real-world factors.</p>`,'agents');
const GROUPS=[{name:'Cells & tiny life',quarter:'Quarter 3 • start here',ids:[0,1,2,3,4,5,6,7]},{name:'Thinking like a scientist',quarter:'Quarter 1 • inquiry & physics',ids:[8,9,10,11,12,13]},{name:'Earth, water & weather',quarter:'Quarter 2',ids:[14,15,16,17,18]},{name:'Earth’s changing surface',quarter:'Quarter 3',ids:[19,20]},{name:'Living systems',quarter:'Quarter 4',ids:[21,22,23,24]}];
const EXTRA = {
8:[['A student changes ramp height and measures car distance. What is the independent variable?','Ramp height','Travel distance|The stopwatch|The result','The independent variable is intentionally changed.'],['In that ramp experiment, what is the dependent variable?','Car travel distance','Ramp height|The car kept the same|The surface kept the same','The dependent variable is the measured result.'],['Which is a controlled variable in the ramp test?','Using the same car','Changing ramp height|Measuring distance|Comparing averages','The same car helps keep the comparison fair.'],['Why change only one factor in a simple fair test?','To connect the result to that factor','To guarantee the expected result|To avoid measuring|To remove all variation','Changing many factors makes the cause of a difference harder to identify.'],['A useful hypothesis must be…','Testable with evidence','Impossible to check|Always correct|A personal preference','Evidence can support or challenge a testable idea.'],['The results disagree with a hypothesis. What should a scientist do?','Review the evidence and revise the explanation if needed','Erase the results|Change the measurements|Claim the test proves everything','Unexpected evidence is useful; report it honestly.'],['What makes methods useful to another investigator?','Enough detail to repeat the investigation','Only the final answer|Only an opinion|Leaving out measurements','Clear methods support replication.'],['Which is a measured result in a plant-growth investigation?','Height after two weeks','The amount of light changed|The identical pots|The chosen plant type','Height is the outcome measured in this investigation.']],
9:[['Which statement is an observation?','The leaf is 8 cm long.','The leaf grew because it was sunny.|The plant probably needs more water.|The soil may contain nutrients.','A measured length is an observation; explanations about causes are inferences.'],['Which statement is an inference?','The plant may have wilted because it lost water.','The stem bends downward.|The leaf is green.|The pot has a mass of 300 g.','An inference interprets observations.'],['You run your experiment five times. This is…','Repetition','Replication|Classification|Condensation','Repeated trials by the same investigator are repetition.'],['Another team follows your methods. This is…','Replication','Repetition only|An independent variable|Deposition','Replication involves another investigator checking the methods and results.'],['Why use multiple trials?','To see variation and improve confidence in the pattern','To guarantee zero errors|To prove every inference|To avoid collecting data','Repeated results help reveal consistency and variation.'],['One trial differs greatly from the others. What is a sensible next step?','Check methods and possible errors, and report the data','Delete it automatically|Hide the trial|Stop measuring forever','Investigate unusual results rather than erasing inconvenient evidence.'],['A student says “I measured a temperature of 25 °C.” That is…','An observation','An inference|A theory|A prediction','A temperature reading is instrument-based observation.'],['Which best supports a claim?','Relevant measurements from repeated trials','A guess with no evidence|An attractive diagram only|Changing results to match a prediction','Claims should be supported by relevant evidence.']],
10:[['What does a scientific theory do?','Explains patterns using extensive evidence','Describes an unsupported guess|Becomes a law after ten tests|Avoids all evidence','Scientific theories are broad evidence-based explanations.'],['What does a scientific law usually describe?','A consistent pattern or relationship','A scientist’s personal preference|Only cell colors|An untested story','Laws describe patterns; theories provide explanations.'],['Does a supported theory eventually become a law?','No; they serve different roles.','Yes, always.|Only after one trial.|Only if written as a sentence.','A theory does not turn into a law; explanation and description are different roles.'],['Why use a model?','To represent a system and make predictions','To include every detail perfectly|To replace all observations|To guarantee an answer','Models simplify systems and help scientists reason about them.'],['Which is a limitation of a cell diagram?','Its colors and sizes may differ from real cells','It can show structures|It can help compare cells|It can have labels','Diagrams are simplified representations, not exact portraits.'],['Which response fits new evidence that contradicts an explanation?','Evaluate and revise the explanation','Ignore all new data|Erase the evidence|Change the instruments’ readings','Science responds to new evidence.'],['Which is an example of a scientific theory?','Cell theory','A favorite food|One ruler measurement|A guess about tomorrow’s lunch','Cell theory is a broad explanation supported by extensive observations.'],['Which statement about scientific models is best?','All models leave out some details','Models are always the real object|Models cannot be revised|Only drawings can be models','Models can be physical, mathematical, or conceptual and have limitations.']],
11:[['A 10 N force right and 4 N force left act on a cart. Net force?','6 N right','14 N right|6 N left|0 N','Opposite forces subtract; the direction is that of the larger force.'],['A cart has 5 N right and 5 N left. The forces are…','Balanced','Unbalanced right|Unbalanced left|Both absent','Equal opposite forces give zero net force.'],['With zero net force, a moving object can…','Keep moving at constant speed in a straight line','Always stop immediately|Always speed up|Always turn','Balanced forces do not change velocity.'],['Which is a contact force?','Friction','Gravity|Magnetism|Gravitational attraction','Friction acts through contact between surfaces.'],['Which can act at a distance?','Gravity','A hand pushing a cart|Friction|A rope pulling a box','Gravity acts between masses without contact.'],['An unbalanced force can change…','Speed or direction','Only the object’s color|Only its name|Nothing about motion','A net force can change velocity, which includes speed and direction.'],['Two forces of 3 N and 4 N act to the right. Net force?','7 N right','1 N left|0 N|12 N right','Forces in the same direction add.'],['Friction usually resists…','Relative sliding between surfaces','The existence of mass|All gravity|Only light','Friction opposes relative motion or its tendency between contacting surfaces.']],
12:[['A walker travels 20 m in 5 s. Average speed?','4 m/s','25 m/s|100 m/s|0.25 m/s','Average speed is 20 ÷ 5 = 4 m/s.'],['A cyclist travels 60 m in 10 s. Average speed?','6 m/s','70 m/s|600 m/s|0.6 m/s','Divide distance by time: 60 ÷ 10 = 6.'],['A flat section on a distance-traveled vs. time graph means…','The object is stopped','The object is fastest|The object reverses direction|Time stops','Distance does not increase during that interval.'],['A steeper upward distance-time slope indicates…','A faster speed','A slower speed|No motion|A different direction necessarily','More distance per unit time means greater speed.'],['A straight sloping distance-time line means…','Constant speed','Increasing speed|Decreasing speed|No motion','A constant slope means equal distances in equal times.'],['Which graph can reveal a reversal of direction in straight-line motion?','Position vs. time','Accumulated distance vs. time alone|Mass vs. temperature|A classification chart','A position-time slope changing sign can indicate reversal.'],['Distance goes from 4 m at 1 s to 16 m at 4 s. Speed in that interval?','4 m/s','5 m/s|12 m/s|20 m/s','Change in distance is 12 m; change in time is 3 s; 12 ÷ 3 = 4.'],['Why can accumulated distance not decrease?','It totals all distance already traveled','An object cannot turn|Speed must always increase|Time graphs are always flat','Turning back still adds traveled distance. Position, however, can decrease.']],
13:[['Which has kinetic energy?','A rolling ball','A motionless raised ball only|A still stretched band only|A stationary book only','Kinetic energy is associated with motion.'],['Which stores gravitational potential energy?','A book raised above the floor','A book’s color|A sound after it stops|An empty label','Position in a gravitational field is associated with potential energy.'],['As a ball falls in an ideal model, potential energy…','Changes into kinetic energy','Is destroyed|Becomes new mass only|Always increases','Potential energy decreases as kinetic energy increases.'],['A battery-powered lamp changes chemical energy into…','Electrical, light, and thermal energy','Only new matter|Nothing|Only gravitational potential energy','Real lamps give off light and thermal energy.'],['Energy spreading as thermal energy is…','Transferred, not destroyed','Destroyed forever|Created from nothing|Not energy anymore','Conservation still applies when energy spreads into the surroundings.'],['The law of conservation of energy says energy…','Cannot be created or destroyed','Always remains in the same form|Can never move between objects|Disappears when a ball stops','Energy transfers and transforms while total energy is conserved.'],['A stretched rubber band stores…','Elastic potential energy','Only kinetic energy while still|No energy|Only light energy','Its stretched arrangement stores elastic potential energy.'],['In a real rolling-ball system, some mechanical energy becomes…','Thermal energy because of friction','Nothing|New sunlight|An organism','Friction can transform mechanical energy into thermal energy.']],
14:[['Which sphere includes rocks and soil?','Geosphere','Biosphere|Atmosphere|Hydrosphere','The geosphere includes Earth’s solid materials.'],['Which sphere includes living organisms?','Biosphere','Geosphere|Atmosphere|Only hydrosphere','The biosphere includes life.'],['Which sphere includes oceans and groundwater?','Hydrosphere','Atmosphere only|Biosphere only|Only geosphere','The hydrosphere includes water in many locations and states.'],['Which sphere contains the gases around Earth?','Atmosphere','Geosphere|Biosphere|A cell wall','The atmosphere is the surrounding layer of gases.'],['Rain washing soil into a stream directly connects…','Hydrosphere and geosphere','Only biosphere|Only atmosphere|No spheres','Water transports solid Earth material.'],['A tree absorbing soil water connects…','Biosphere and hydrosphere','Only atmosphere|Only geosphere|No systems','A living organism takes up water.'],['A single Earth event can involve…','Several spheres at once','Exactly one sphere|No physical materials|Only living things','Earth systems interact.'],['Ice belongs to the hydrosphere because…','It is water in solid form','It is always alive|It is a gas|It contains no water','The hydrosphere includes frozen water.']],
15:[['Which gas makes up most of Earth’s atmosphere?','Nitrogen','Oxygen|Carbon dioxide|Helium','Air is about 78% nitrogen and 21% oxygen.'],['Where does most weather occur?','Troposphere','Exosphere|Thermosphere|Mesosphere','The lowest atmospheric layer contains most weather.'],['The main ozone layer is in the…','Stratosphere','Troposphere|Exosphere|Geosphere','The stratospheric ozone layer absorbs much harmful ultraviolet radiation.'],['Air pressure generally does what with increasing altitude?','Decreases','Increases|Always stays identical|Becomes solid','There is less air above you at higher altitudes.'],['Which layer is nearest Earth’s surface?','Troposphere','Mesosphere|Exosphere|Thermosphere','The layer order begins with the troposphere.'],['Which layer comes above the stratosphere?','Mesosphere','Troposphere|Hydrosphere|Biosphere','The sequence is troposphere, stratosphere, mesosphere, thermosphere, exosphere.'],['What does the ozone layer help absorb?','Ultraviolet radiation','All gravity|All oxygen|Every kind of sound','Ozone absorbs much of the Sun’s harmful UV radiation.'],['Which is true of atmospheric temperature?','It does not decrease steadily through every layer','It always decreases at every altitude|It is identical everywhere|It cannot be measured','Different layers have different temperature trends.']],
16:[['Sunlight warming sand is mainly…','Radiation','Conduction|Convection|Cell division','Electromagnetic waves carry energy from the Sun.'],['Warm sand warming bare feet by contact is…','Conduction','Radiation only|Convection|Condensation','Conduction transfers thermal energy through direct contact.'],['Warm air rising and cooler air sinking is…','Convection','Conduction only|Deposition|Classification','Convection transfers energy through fluid movement.'],['Which transfer can occur across empty space?','Radiation','Conduction|Convection|Diffusion of air','Electromagnetic waves do not need matter.'],['Thermal energy naturally transfers from…','Warmer to cooler regions','Cooler to warmer without other changes|No region to another|Only living to nonliving things','Thermal energy tends to transfer down a temperature difference.'],['A metal spoon warms where it touches warm soup. The spoon’s transfer is mainly…','Conduction','Osmosis|Photosynthesis|Replication','Contact transfers energy into and along the metal.'],['Why does warmer air often rise?','It becomes less dense than surrounding cooler air','It has no mass|It turns into sunlight|Gravity disappears','Temperature-related density differences contribute to convection.'],['Can more than one heat-transfer process happen together?','Yes','No, never|Only in cells|Only in space','Real situations often involve conduction, convection, and radiation together.']],
17:[['Liquid water becoming vapor is…','Evaporation','Condensation|Deposition of sediment|Precipitation','Evaporation changes liquid water into gas.'],['Water vapor becoming liquid droplets is…','Condensation','Evaporation|Runoff|Infiltration','Condensation forms liquid from vapor.'],['Rain falling from clouds is…','Precipitation','Transpiration|Infiltration|Evaporation','Precipitation is water falling from the atmosphere.'],['Water vapor leaving plant leaves is…','Transpiration','Deposition|Erosion|Conduction','Plants release water vapor mainly through leaves.'],['The main energy source driving evaporation in the global water cycle is…','The Sun','The Moon’s light|Cell walls|Groundwater itself','Solar energy powers much evaporation.'],['Water soaking into soil is…','Infiltration','Condensation|Radiation|Photosynthesis','Infiltration moves surface water into soil.'],['What helps drive falling rain and downhill runoff?','Gravity','Chloroplasts|Ribosomes|Only magnetism','Gravity moves water downward.'],['Clouds mainly contain…','Tiny liquid droplets or ice crystals','Only invisible water vapor|Only smoke|Only oxygen atoms','Cloud particles are liquid droplets or ice crystals.']],
18:[['Tomorrow’s chance of rain describes…','Weather','Climate|Cell theory|A domain','Weather is short-term atmospheric conditions.'],['Average seasonal patterns over decades describe…','Climate','One day’s weather|A single storm|One microscope reading','Climate describes long-term patterns.'],['A major cause of global winds is…','Uneven solar heating and resulting pressure differences','Identical temperatures everywhere|Cell division|No atmosphere','Uneven heating drives temperature and pressure differences.'],['Earth’s rotation affects…','Large-scale wind and current directions','Only cell colors|Only rainfall chemistry|No air or water motion','Rotation deflects large-scale movement.'],['During a typical daytime sea breeze, surface air often moves…','From sea toward land','From land toward sea|Only upward over the sea|Nowhere','Land warms faster, air over land rises, and cooler air moves in from the sea.'],['Jet streams are…','Fast winds high in the atmosphere','Rivers underground|Deep-ocean rocks|Large cells','Jet streams can help steer weather systems.'],['Ocean currents can…','Redistribute thermal energy','Destroy all energy|Stop all winds|Change water into rocks','Currents transport warmer and cooler water.'],['Can one unusual storm establish a region’s climate?','No; climate needs long-term patterns','Yes, always|Only if it rains hard|Only if winds stop','One event is weather; climate concerns patterns over long periods.']],
19:[['Water freezing in a rock crack and splitting it is…','Physical weathering','Chemical weathering|Deposition|Photosynthesis','The rock breaks without a chemical change to its minerals.'],['Acid reacting with limestone is…','Chemical weathering','Physical weathering only|Deposition|Classification','The minerals chemically change.'],['A river carrying sediment is…','Erosion','Weathering only|Deposition|Replication','Erosion is movement of material.'],['Sediment settling when water slows is…','Deposition','Erosion|Photosynthesis|Cell division','Deposition is material being laid down.'],['Weathering differs from erosion because weathering…','Breaks down rock where it is','Only carries rock away|Only settles rock|Only forms cells','Weathering breaks down; erosion transports.'],['Roots widening a rock crack are an example of…','Physical weathering','Only condensation|Only radiation|Only deposition','Roots can physically split rock.'],['Which order matches break, move, settle?','Weathering, erosion, deposition','Deposition, erosion, weathering|Erosion, deposition, weathering|Weathering, deposition, erosion','These processes describe different steps in changing a landscape.'],['Can physical and chemical weathering act together?','Yes','No, never|Only in animals|Only without water','Rock can undergo both kinds of weathering.']],
20:[['A delta commonly forms when a river…','Deposits sediment as it enters slower water','Evaporates all its water|Turns into a glacier|Stops having gravity','A slowing river can deposit sediment at its mouth.'],['Wind depositing sand can form…','Dunes','Nuclei|Mitochondria|Only glaciers','Dunes are accumulations of wind-deposited sand.'],['A river cutting a canyon is mainly…','Erosion','Cell division|Condensation|Classification','Flowing water removes material over time.'],['A landslide is driven downhill mainly by…','Gravity','Photosynthesis|Only magnetism|DNA','Gravity moves unstable material downslope.'],['Closely spaced contour lines show…','A steep slope','A gentle slope|Zero elevation|A new cell','Elevation changes quickly over a short horizontal distance.'],['Widely spaced contour lines show…','A gentler slope','A steeper slope|Only oceans|Only cliffs','The same elevation change occurs over more horizontal distance.'],['Contour lines connect points of equal…','Elevation','Temperature|Cell number|Speed','Topographic maps use lines of equal elevation.'],['A transporting stream slows. What often happens?','Some sediment settles','All sediment speeds up|Gravity ends|Water becomes a gas instantly','Slower flow often carries less sediment.']],
21:[['Which is the broadest group listed?','Domain','Genus|Species|Family','Domain is broader than kingdom and the other categories.'],['Which list names the three domains?','Bacteria, Archaea, Eukarya','Plants, animals, fungi|Genus, species, tissue|Air, water, land','The three-domain system uses Bacteria, Archaea, and Eukarya.'],['Which domain includes plants and animals?','Eukarya','Bacteria|Archaea|Hydrosphere','Plant and animal cells have nuclei and belong to Eukarya.'],['In Homo sapiens, Homo is the…','Genus','Species word|Kingdom|Domain','Scientific names combine genus and species.'],['Which pair is ordered broad to specific?','Genus → species','Species → domain|Family → kingdom|Class → phylum','Species is a more specific category than genus.'],['Which groups have cells without nuclei?','Bacteria and Archaea','Only animals|Only plants|All Eukarya','Bacteria and Archaea have prokaryotic cells without nuclei.'],['A useful classification key uses…','Observable distinguishing characteristics','Favorite colors only|Random guesses|Only size of the page','Keys use trait-based decisions to separate organisms.'],['Two organisms share a genus rather than only a kingdom. They share…','A more specific classification group','A broader group|No classification|Exactly the same individual body','Genus is more specific than kingdom.']],
22:[['Which system breaks food down and absorbs nutrients?','Digestive','Respiratory|Skeletal|Nervous','Digestive processes supply nutrients to the body.'],['Which system exchanges oxygen and carbon dioxide?','Respiratory','Skeletal|Reproductive|Integumentary','The respiratory system exchanges these gases with the environment.'],['Which system transports oxygen and nutrients in blood?','Circulatory','Skeletal|Digestive only|Reproductive','Blood and the circulatory system carry materials to cells.'],['Kidneys filtering blood and producing urine belong to which function?','Excretory','Skeletal|Only nervous|Only respiratory','Excretion removes dissolved metabolic wastes and helps manage water balance.'],['Which systems directly cooperate to deliver oxygen to muscle cells?','Respiratory and circulatory','Reproductive and skeletal|Digestive and reproductive|Immune and skeletal','Lungs exchange gases and circulation transports them.'],['During exercise, breathing and heart rate often increase to…','Supply working cells and help remove wastes','Make cells stop using energy|Eliminate all oxygen|Turn cells into tissues instantly','Working muscles need increased delivery of oxygen and nutrients.'],['Which system produces reproductive cells?','Reproductive','Digestive|Excretory|Skeletal','Reproductive systems enable production of offspring.'],['Undigested food and dissolved metabolic wastes leave through…','Different processes involving digestive and excretory functions','Exactly the same kidney process|Only the nervous system|Only skin','The digestive tract eliminates undigested food; kidneys remove metabolic wastes from blood.']],
23:[['Which system coordinates responses using nerve signals?','Nervous','Digestive|Excretory|Reproductive','Nerves and the brain coordinate sensing and responses.'],['Bones supporting the body belong to the…','Skeletal system','Digestive system|Respiratory system|Excretory system','The skeleton provides support and protects organs.'],['Which system contracts to move body parts?','Muscular','Immune|Reproductive|Excretory','Muscles contract and work with the skeleton.'],['Which system helps defend against pathogens?','Immune','Digestive only|Skeletal only|Reproductive','The immune system provides defenses against infectious agents.'],['Skin, hair, and nails form the…','Integumentary system','Circulatory system|Respiratory system|Excretory system only','The integumentary system provides protection and helps regulate temperature.'],['Moving your arm involves which pair directly working together?','Muscular and skeletal','Digestive and reproductive|Excretory and respiratory only|Immune and digestive','Muscles pull on bones to produce movement.'],['Sweat evaporating can help the body…','Cool down','Destroy all energy|Stop having cells|Make a cell wall','Evaporation removes thermal energy from skin.'],['Body systems maintain homeostasis by…','Working together to keep conditions within useful ranges','Working entirely independently|Making all cells identical|Keeping every value exactly fixed','Homeostasis relies on coordinated systems and ranges rather than perfect constancy.']],
24:[['Which infectious agent is not a cell and needs host cells to reproduce?','Virus','Bacterium|Fungus|A multicellular parasite','Viruses use host cells to make more virus particles.'],['Bacteria are…','Single-celled organisms without nuclei','Always multicellular|All disease-causing|Not cells','Bacteria are prokaryotic cells; many do not cause disease.'],['Yeasts and molds belong to which group?','Fungi','Viruses|Only bacteria|Only animals','Fungi have cells with nuclei and include yeasts and molds.'],['A parasite benefits while…','Living on or in a host at the host’s expense','Helping every host always|Being a nonliving atom|Replacing sunlight','Parasitism is a relationship that benefits the parasite and harms the host.'],['Antibiotics act against certain…','Bacterial infections','Viral infections|All illnesses|Every parasite','Antibiotics do not treat viruses. Medicine decisions belong with a responsible adult and healthcare professional.'],['Are all microorganisms harmful?','No; many are useful or harmless','Yes, all cause disease|Yes, all are viruses|No microorganisms are living','Many microorganisms help ecosystems and living organisms.'],['What can help reduce infectious-agent spread?','Handwashing','Sharing every personal item|Ignoring coughs|Guessing medicine doses','Handwashing can reduce transfer of infectious agents.'],['Can one symptom reliably identify the infectious agent?','No; more evidence is needed','Yes, always|Only if the person is young|Only if the symptom is a cough','Different agents can cause similar symptoms; do not diagnose from one sign.']]
};
for(const [k,rows] of Object.entries(EXTRA))for(const row of rows)Q(+k,row[0],row[1],row[2].split('|'),row[3]);
LESSONS[0].body+=`<details><summary><strong>Cell-theory scientists</strong></summary><ul><li><strong>Robert Hooke:</strong> described tiny compartments in cork and called them “cells.” He observed the walls of dead cork cells.</li><li><strong>Antonie van Leeuwenhoek:</strong> observed living microscopic organisms.</li><li><strong>Matthias Schleiden:</strong> concluded plants are made of cells.</li><li><strong>Theodor Schwann:</strong> concluded animals are made of cells.</li><li><strong>Rudolf Virchow:</strong> helped popularize the idea that cells arise from existing cells.</li></ul></details>`;
Q(0,'Who named the compartments he observed in cork “cells”?','Robert Hooke',['Theodor Schwann','Matthias Schleiden','Rudolf Virchow'],'Hooke described the compartments in cork; he observed dead cell walls.');
Q(0,'Which scientist observed living microscopic organisms?','Antonie van Leeuwenhoek',['Matthias Schleiden','Theodor Schwann','Robert Hooke in his cork observation'],'Van Leeuwenhoek observed living microscopic organisms using microscopes.');
Q(0,'Schleiden and Schwann helped establish that…','Plants and animals are made of cells.',['Every cell has chloroplasts.','All life is noncellular.','Atoms are organs.'],'Schleiden studied plant cells and Schwann studied animal cells.');
const STUDY = [...ORG.map(o=>({topic:4,front:o.name,back:o.job})),...LESSONS.map((l,i)=>({topic:i,front:l.title,back:l.goal+' '+l.terms})),
{topic:0,front:'Three ideas of cell theory',back:'Organisms are made of cells. Cells are the basic unit of life. New cells come from existing cells.'},
{topic:6,front:'Levels of organization',back:'Atom → molecule → cell → tissue → organ → organ system → organism.'},
{topic:12,front:'Average speed',back:'Total distance ÷ total time. Include units, such as m/s.'},
{topic:16,front:'Three thermal transfers',back:'Conduction: direct contact. Convection: moving fluid. Radiation: electromagnetic waves.'},
{topic:8,front:'Investigation variables',back:'Independent: change it. Dependent: measure it. Controlled: keep it alike.'},
{topic:9,front:'Repetition vs. replication',back:'Repetition: your repeated trials. Replication: others repeat your methods.'},
{topic:21,front:'Classification order',back:'Domain, kingdom, phylum, class, order, family, genus, species.'}];
FAQ.push(['How do I study another unit?', 'Every unit has its own learning path. Start with the first lesson in any unit. Earn 80% on a lesson quiz to unlock the next in that unit. Cells is ready to start immediately.'],['Observation or inference?', 'An observation is what you see or measure. An inference is an explanation based on those observations. “The plant is bent” is observation. “It may need water” is inference.'],['How do I read a motion graph?', 'Time goes on the horizontal axis. On a distance-traveled graph, flat means stopped and steeper means faster. That graph alone cannot show direction. A position-time graph can show reversals when its slope changes sign.'],['Conduction, convection, or radiation?', 'Contact: conduction. Circulating air or water: convection. Electromagnetic waves such as sunlight: radiation. Several can happen in one situation.'],['Where does weather get its energy?', 'The Sun heats Earth unevenly, driving temperature and pressure differences that help move air and water. Solar energy drives much evaporation; gravity drives precipitation and runoff.']);
