const G={
0:`<div class="game"><h3>⚡ Lattice Lab</h3><p>Change charge and distance and watch electrostatic attraction respond.</p><div class="ions"><span id="ionA">+</span><span class="force" id="force">↔</span><span id="ionB">−</span></div><label>Ion charge: <b id="chgVal">1</b><input id="chg" type="range" min="1" max="3" step="1" value="1"><div><button class="mini" id="chgDown">− charge</button><button class="mini" id="chgUp">+ charge</button></div></label><label>Distance: <b id="distVal">3</b><input id="dist" type="range" min="1" max="5" step="1" value="3"><div><button class="mini" id="distDown">Closer</button><button class="mini" id="distUp">Farther</button></div></label><p id="read"></p></div>`,
2:`<div class="game"><h3>🔗 Bond Builder</h3><p>Tap a bond order to see σ/π composition and the strength/length trend.</p><div class="bondviz"><span>●</span><span id="lines">—</span><span>●</span></div><div><button class="mini" data-bo="1">Single</button><button class="mini" data-bo="2">Double</button><button class="mini" data-bo="3">Triple</button></div><p id="bondread"></p></div>`,
3:`<div class="game"><h3>🎢 Bond Energy Simulator</h3><p>Move the atoms. Try to find the stable bond distance.</p><p>Separation: <b id="sepVal">75</b></p><input id="sep" type="range" min="1" max="100" step="1" value="75"><div><button class="mini" id="sepDown">Move closer</button><button class="mini" id="sepUp">Move farther</button></div><div class="atoms"><span>●</span><i id="gap"></i><span>●</span></div><div class="meter"><i id="energy"></i></div><p id="energyread"></p></div>`,
7:`<div class="game"><h3>🧬 Shape Shifter</h3><p>Choose electron domains and lone pairs to predict molecular shape.</p><label>Domains <select id="domains"><option>2</option><option>3</option><option selected>4</option><option>5</option><option>6</option></select></label><label>Lone pairs <select id="lone"><option>0</option><option>1</option><option>2</option><option>3</option></select></label><div class="shape" id="shape"></div><p id="shaperead"></p></div>`
};
function initGame(i){if(i===0){let go=()=>{let q=+$("#chg").value,d=+$("#dist").value,f=(q*q)/(d*d);$("#chgVal").textContent=q;$("#distVal").textContent=d;$("#ionA").textContent=q+"+";$("#ionB").textContent=q+"−";$("#force").style.transform="scaleX("+Math.min(2.2,.7+f)+")";$("#read").innerHTML="<b>Relative attraction: "+f.toFixed(2)+"</b> — larger charge strengthens attraction; greater distance weakens it.";};$("#chg").oninput=$("#dist").oninput=go;$("#chgDown").onclick=()=>{$("#chg").value=Math.max(1,+$("#chg").value-1);go()};$("#chgUp").onclick=()=>{$("#chg").value=Math.min(3,+$("#chg").value+1);go()};$("#distDown").onclick=()=>{$("#dist").value=Math.max(1,+$("#dist").value-1);go()};$("#distUp").onclick=()=>{$("#dist").value=Math.min(5,+$("#dist").value+1);go()};go()}if(i===2){let go=n=>{let names=["","1 σ bond","1 σ + 1 π","1 σ + 2 π"];$("#lines").textContent=["","—","═","≡"][n];$("#bondread").innerHTML="<b>"+names[n]+"</b>. Higher bond order is generally shorter and stronger.";};document.querySelectorAll("[data-bo]").forEach(b=>b.onclick=()=>go(+b.dataset.bo));go(1)}if(i===3){let go=()=>{let x=+$("#sep").value;$("#sepVal").textContent=x;$("#gap").style.width=(15+x*1.8)+"px";let e=Math.min(100,Math.abs(x-48)*2.5);$("#energy").style.width=e+"%";$("#energyread").textContent=x<35?"Too close: repulsion rises sharply.":x>62?"Too far: attraction weakens.":"Near the energy minimum: a stable bond distance.";};$("#sep").oninput=go;$("#sepDown").onclick=()=>{$("#sep").value=Math.max(1,+$("#sep").value-5);go()};$("#sepUp").onclick=()=>{$("#sep").value=Math.min(100,+$("#sep").value+5);go()};go()}if(i===7){let go=()=>{let d=+$("#domains").value,l=+$("#lone").value,key=d+"-"+l,map={"2-0":"Linear • 180°","3-0":"Trigonal planar • 120°","3-1":"Bent","4-0":"Tetrahedral • 109.5°","4-1":"Trigonal pyramidal","4-2":"Bent","5-0":"Trigonal bipyramidal","5-1":"Seesaw","5-2":"T-shaped","5-3":"Linear","6-0":"Octahedral","6-1":"Square pyramidal","6-2":"Square planar"};let s=map[key]||"Choose a valid VSEPR combination";$("#shape").textContent=s.split(" • ")[0];$("#shaperead").innerHTML="<b>"+s+"</b>. Molecular geometry describes atom positions; lone pairs still control repulsion.";};$("#domains").onchange=$("#lone").onchange=go;go()}}

const MISSIONS=[
{f:"H₂O",e:8,b:2,l:2,s:"Bent",why:"Oxygen has two O–H bonds and two lone pairs: four electron domains, AX₂E₂."},
{f:"NH₃",e:8,b:3,l:1,s:"Trigonal pyramidal",why:"Nitrogen has three N–H bonds and one lone pair: AX₃E."},
{f:"CO₂",e:16,b:4,l:0,s:"Linear",why:"Two C=O double bonds count as two electron domains around carbon, so CO₂ is linear."},
{f:"CH₄",e:8,b:4,l:0,s:"Tetrahedral",why:"Carbon has four bonding domains and no lone pairs: AX₄."},
{f:"BF₃",e:24,b:3,l:0,s:"Trigonal planar",why:"Boron has three bonding domains and no lone pairs; BF₃ is an octet exception."}
];
function missionGame(){let game={i:0,score:0,lives:3,streak:0};function draw(){let m=MISSIONS[game.i%MISSIONS.length];$("#main").innerHTML='<div class="game mission"><span class="pill">Molecule Mission</span><h2>Build '+m.f+'</h2><p>Configure the molecule correctly. You have '+game.lives+' ♥ • Score '+game.score+' • Streak '+game.streak+'</p><div class="molecule-orbit"><b>'+m.f+'</b><i></i><i></i><i></i></div><div class="missiongrid"><label>Total valence electrons<select id="me"><option>8</option><option>16</option><option>24</option><option>32</option></select></label><label>Total bond order around center<select id="mb"><option>2</option><option>3</option><option>4</option><option>5</option></select></label><label>Lone pairs on central atom<select id="ml"><option>0</option><option>1</option><option>2</option><option>3</option></select></label><label>Molecular geometry<select id="ms"><option>Linear</option><option>Bent</option><option>Trigonal planar</option><option>Trigonal pyramidal</option><option>Tetrahedral</option></select></label></div><button class="go" id="launch">Lock In Answer</button><button class="mini" id="exit">Back to lesson</button><div id="missionfb"></div></div>';$("#exit").onclick=lesson;$("#launch").onclick=()=>{let ok=+$("#me").value===m.e&&+$("#mb").value===m.b&&+$("#ml").value===m.l&&$("#ms").value===m.s;let f=$("#missionfb");if(ok){game.score+=100+game.streak*25;game.streak++;f.className="fb good";f.innerHTML="<b>Mission complete! +"+(100+(game.streak-1)*25)+" points</b><br>"+m.why+'<br><button class="go" id="nextmission">Next molecule</button>';$("#nextmission").onclick=()=>{game.i++;draw()}}else{game.lives--;game.streak=0;f.className="fb bad";if(game.lives<=0){f.innerHTML="<b>Reactor reset.</b> "+m.why+'<br><button class="go" id="retrymission">Try this molecule again</button>';$("#retrymission").onclick=()=>{game.lives=3;draw()}}else f.innerHTML="<b>Not stable yet.</b> Check electron counting, the central atom’s lone pairs, and VSEPR. "+game.lives+" ♥ remaining."}}}draw()}
