const G={
0:`<div class="game challenge"><div class="challenge-title"><span>⚡</span><div><small>MISSION 01</small><h3>Build the Strongest Crystal</h3></div></div><p class="mission-text">Your goal: make the attraction score reach <b>9.00</b>. You control the ion charge and the distance between the ions.</p><div class="goalbar"><span>Target: 9.00</span><b id="goalStatus">Keep experimenting</b></div><div class="ions"><span id="ionA">+</span><span class="force" id="force">↔</span><span id="ionB">−</span></div><div class="control-card"><label>Charge on each ion <b id="chgVal">1</b><input id="chg" type="range" min="1" max="3" step="1" value="1"></label><div><button class="mini" id="chgDown">− charge</button><button class="mini" id="chgUp">+ charge</button></div><p class="hintline">Bigger charges act like stronger magnets.</p></div><div class="control-card"><label>Distance between ions <b id="distVal">3</b><input id="dist" type="range" min="1" max="5" step="1" value="3"></label><div><button class="mini" id="distDown">Move closer</button><button class="mini" id="distUp">Move farther</button></div><p class="hintline">Closer opposite charges pull harder.</p></div><div class="scorebox">Attraction score <strong id="readScore">0.11</strong></div><button class="go mission-check" id="latticeCheck">Check My Answer</button><button class="mini" id="latticeHint">I’m stuck — give me a hint</button><div id="latticeResult"></div></div>`,
2:`<div class="game challenge"><div class="challenge-title"><span>🔗</span><div><small>MISSION 02</small><h3>Build a Triple Bond</h3></div></div><p class="mission-text">Goal: choose the bond that contains <b>1 sigma (σ) + 2 pi (π)</b> bonds.</p><div class="bondviz"><span>●</span><span id="lines">—</span><span>●</span></div><div><button class="mini" data-bo="1">Single</button><button class="mini" data-bo="2">Double</button><button class="mini" data-bo="3">Triple</button></div><p id="bondread"></p><button class="mini" id="bondHint">Need a hint?</button><div id="bondResult"></div></div>`,
3:`<div class="game challenge"><div class="challenge-title"><span>🎢</span><div><small>MISSION 03</small><h3>Find the Bond Sweet Spot</h3></div></div><p class="mission-text">Goal: move the atoms until they reach the stable zone — <b>not too close and not too far</b>.</p><p>Separation: <b id="sepVal">75</b></p><input id="sep" type="range" min="1" max="100" step="1" value="75"><div><button class="mini" id="sepDown">Move closer</button><button class="mini" id="sepUp">Move farther</button></div><div class="atoms"><span>●</span><i id="gap"></i><span>●</span></div><div class="meter"><i id="energy"></i></div><p id="energyread"></p><button class="go" id="energyCheck">Check My Answer</button><button class="mini" id="energyHint">I’m stuck</button><div id="energyResult"></div></div>`,
7:`<div class="game challenge"><div class="challenge-title"><span>🧬</span><div><small>MISSION 04</small><h3>Shape Challenge: Water</h3></div></div><p class="mission-text">Water (H₂O) has <b>4 electron domains</b> around oxygen and <b>2 lone pairs</b>. Set those values to discover its molecular shape.</p><label>Electron domains <select id="domains"><option>2</option><option>3</option><option selected>4</option><option>5</option><option>6</option></select></label><label>Lone pairs <select id="lone"><option>0</option><option>1</option><option>2</option><option>3</option></select></label><div class="shape" id="shape"></div><p id="shaperead"></p><button class="go" id="shapeCheck">Check Water’s Shape</button><button class="mini" id="shapeHint">Need a hint?</button><div id="shapeResult"></div></div>`
};
const LAB_LESSONS=[0,2,3,7];
function anotherLab(current){
  const next=LAB_LESSONS[(LAB_LESSONS.indexOf(current)+1)%LAB_LESSONS.length];
  cur=next;
  lesson();
  document.querySelector("#main .challenge").scrollIntoView({behavior:"smooth",block:"start"});
}
function labComplete(box,i){
  const button=document.createElement("button");
  button.type="button";
  button.className="go another-lab";
  button.textContent="Do another lab";
  button.onclick=()=>anotherLab(i);
  box.append(button);
}
function initGame(i){
if(i===0){let go=()=>{let q=+$("#chg").value,d=+$("#dist").value,f=(q*q)/(d*d);$("#chgVal").textContent=q;$("#distVal").textContent=d;$("#ionA").textContent=q+"+";$("#ionB").textContent=q+"−";$("#force").style.transform="scaleX("+Math.min(2.2,.7+f)+")";$("#readScore").textContent=f.toFixed(2);$("#goalStatus").textContent=f>=9?"TARGET REACHED!":"Target: 9.00"};$("#chg").oninput=$("#dist").oninput=go;$("#chgDown").onclick=()=>{$("#chg").value=Math.max(1,+$("#chg").value-1);go()};$("#chgUp").onclick=()=>{$("#chg").value=Math.min(3,+$("#chg").value+1);go()};$("#distDown").onclick=()=>{$("#dist").value=Math.max(1,+$("#dist").value-1);go()};$("#distUp").onclick=()=>{$("#dist").value=Math.min(5,+$("#dist").value+1);go()};$("#latticeHint").onclick=()=>{let q=+$("#chg").value,d=+$("#dist").value;$("#latticeResult").className="fb bot";$("#latticeResult").innerHTML=q<3?"<b>Hint 1:</b> Make the charges bigger. Bigger opposite charges pull on each other more strongly.":d>1?"<b>Hint 2:</b> Your charges are strong. Now bring the ions closer. Attraction gets stronger when opposite charges are nearer.":"You have the correct settings — press Check My Answer!"};$("#latticeCheck").onclick=()=>{let q=+$("#chg").value,d=+$("#dist").value,box=$("#latticeResult");if(q===3&&d===1){box.className="fb good";box.innerHTML="<b>Mission complete! 🎉</b><br>You made the strongest attraction: charge 3 and distance 1. <b>Why it works:</b> bigger opposite charges pull harder, and putting them closer makes the pull even stronger. This is the idea behind high lattice energy.";labComplete(box,i)}else{box.className="fb bad";box.innerHTML="<b>Not there yet — and that’s useful.</b><br>"+(q<3?"Your charges are still small. Increase them so the positive and negative ions pull harder. ":"Your charge is already as strong as possible. ")+(d>1?"The ions are still too far apart. Bring them closer so their attraction increases.":"Your distance is correct.")+"<br><b>Try again:</b> change one control, then recheck."}};go()}
if(i===2){let selected=1;let go=n=>{selected=n;let names=["","1 σ bond","1 σ + 1 π","1 σ + 2 π"];$("#lines").textContent=["","—","═","≡"][n];$("#bondread").innerHTML="<b>"+names[n]+"</b>";$("#bondResult").className="fb "+(n===3?"good":"bad");$("#bondResult").innerHTML=n===3?"<b>Mission complete! 🎉</b> A triple bond is 1σ + 2π. The first bond is always sigma; the two extra bonds are pi.":"<b>Not yet.</b> A "+(n===1?"single bond has only the first σ bond. You still need two additional π bonds.":"double bond has 1σ + 1π. You need one more π bond.");if(n===3)labComplete($("#bondResult"),i)};document.querySelectorAll("[data-bo]").forEach(b=>b.onclick=()=>go(+b.dataset.bo));$("#bondHint").onclick=()=>{$("#bondResult").className="fb bot";$("#bondResult").innerHTML="<b>Hint:</b> Start with one sigma bond. Each bond after the first is a pi bond. How many total bonds would give you two pi bonds?"};go(1)}
if(i===3){let go=()=>{let x=+$("#sep").value;$("#sepVal").textContent=x;$("#gap").style.width=(15+x*1.8)+"px";let e=Math.min(100,Math.abs(x-48)*2.5);$("#energy").style.width=e+"%";$("#energyread").textContent=x<35?"Too close: the atoms repel strongly.":x>62?"Too far: the atoms barely attract.":"You are in the stable zone."};$("#sep").oninput=go;$("#sepDown").onclick=()=>{$("#sep").value=Math.max(1,+$("#sep").value-5);go()};$("#sepUp").onclick=()=>{$("#sep").value=Math.min(100,+$("#sep").value+5);go()};$("#energyHint").onclick=()=>{let x=+$("#sep").value;$("#energyResult").className="fb bot";$("#energyResult").innerHTML=x>62?"<b>Hint:</b> The atoms are too far apart. Move them closer so attraction can hold them together.":x<35?"<b>Hint:</b> The atoms are crowded too close and repel. Move them farther apart.":"You are in the right zone — check your answer!"};$("#energyCheck").onclick=()=>{let x=+$("#sep").value,ok=x>=35&&x<=62;$("#energyResult").className="fb "+(ok?"good":"bad");$("#energyResult").innerHTML=ok?"<b>Mission complete! 🎉</b><br>You found the stable region. A bond is most stable at a middle distance where attraction is strong but repulsion has not become too large.":"<b>Not stable yet.</b><br>"+(x<35?"The atoms are too close, so repulsion is winning. Move farther apart.":"The atoms are too far apart, so attraction is too weak. Move closer.");if(ok)labComplete($("#energyResult"),i)};go()}
if(i===7){let go=()=>{let d=+$("#domains").value,l=+$("#lone").value,key=d+"-"+l,map={"2-0":"Linear • 180°","3-0":"Trigonal planar • 120°","3-1":"Bent","4-0":"Tetrahedral • 109.5°","4-1":"Trigonal pyramidal","4-2":"Bent","5-0":"Trigonal bipyramidal","5-1":"Seesaw","5-2":"T-shaped","5-3":"Linear","6-0":"Octahedral","6-1":"Square pyramidal","6-2":"Square planar"};let s=map[key]||"Invalid combination";$("#shape").textContent=s.split(" • ")[0];$("#shaperead").innerHTML="<b>"+s+"</b>"};$("#domains").onchange=$("#lone").onchange=go;$("#shapeHint").onclick=()=>{$("#shapeResult").className="fb bot";$("#shapeResult").innerHTML="<b>Hint:</b> Water’s oxygen has two O–H bonds plus two lone pairs. That makes 4 electron domains total and 2 lone pairs."};$("#shapeCheck").onclick=()=>{let d=+$("#domains").value,l=+$("#lone").value,ok=d===4&&l===2;$("#shapeResult").className="fb "+(ok?"good":"bad");$("#shapeResult").innerHTML=ok?"<b>Mission complete! 🎉 Water is bent.</b><br>The four electron groups spread out, but only two are bonds to H. The two lone pairs push on the bonds, giving H₂O its bent molecular shape.":"<b>Not quite.</b><br>"+(d!==4?"Water needs 4 total electron domains: two bonds plus two lone pairs. ":"Your domain count is right. ")+(l!==2?"Set lone pairs to 2. Those lone pairs are why water is bent instead of tetrahedral.":"");if(ok)labComplete($("#shapeResult"),i)};go()}
}
const MISSIONS=[
{f:"H₂O",e:8,b:2,l:2,s:"Bent",why:"Oxygen has two O–H bonds and two lone pairs: four electron domains, AX₂E₂."},
{f:"NH₃",e:8,b:3,l:1,s:"Trigonal pyramidal",why:"Nitrogen has three N–H bonds and one lone pair: AX₃E."},
{f:"CO₂",e:16,b:4,l:0,s:"Linear",why:"Two C=O double bonds count as two electron domains around carbon, so CO₂ is linear."},
{f:"CH₄",e:8,b:4,l:0,s:"Tetrahedral",why:"Carbon has four bonding domains and no lone pairs: AX₄."},
{f:"BF₃",e:24,b:3,l:0,s:"Trigonal planar",why:"Boron has three bonding domains and no lone pairs; BF₃ is an octet exception."}
];
function missionGame(){let game={i:0,score:0,lives:3,streak:0};function draw(){let m=MISSIONS[game.i%MISSIONS.length];$("#main").innerHTML='<div class="game mission"><span class="pill">Molecule Mission</span><h2>Build '+m.f+'</h2><p>Configure the molecule correctly. You have '+game.lives+' ♥ • Score '+game.score+' • Streak '+game.streak+'</p><div class="molecule-orbit"><b>'+m.f+'</b><i></i><i></i><i></i></div><div class="missiongrid"><label>Total valence electrons<select id="me"><option>8</option><option>16</option><option>24</option><option>32</option></select></label><label>Total bond order around center<select id="mb"><option>2</option><option>3</option><option>4</option><option>5</option></select></label><label>Lone pairs on central atom<select id="ml"><option>0</option><option>1</option><option>2</option><option>3</option></select></label><label>Molecular geometry<select id="ms"><option>Linear</option><option>Bent</option><option>Trigonal planar</option><option>Trigonal pyramidal</option><option>Tetrahedral</option></select></label></div><button class="go" id="launch">Lock In Answer</button><button class="mini" id="exit">Back to lesson</button><div id="missionfb"></div></div>';$("#exit").onclick=lesson;$("#launch").onclick=()=>{let ok=+$("#me").value===m.e&&+$("#mb").value===m.b&&+$("#ml").value===m.l&&$("#ms").value===m.s;let f=$("#missionfb");if(ok){game.score+=100+game.streak*25;game.streak++;f.className="fb good";f.innerHTML="<b>Mission complete! +"+(100+(game.streak-1)*25)+" points</b><br>"+m.why+'<br><button class="go" id="nextmission">Do another lab</button>';$("#nextmission").onclick=()=>{game.i++;draw()}}else{game.lives--;game.streak=0;f.className="fb bad";if(game.lives<=0){f.innerHTML="<b>Reactor reset.</b> "+m.why+'<br><button class="go" id="retrymission">Try this molecule again</button>';$("#retrymission").onclick=()=>{game.lives=3;draw()}}else f.innerHTML="<b>Not stable yet.</b> Check electron counting, the central atom’s lone pairs, and VSEPR. "+game.lives+" ♥ remaining."}}}draw()}
