const HELP=[
{keys:["ion","cation","anion"],a:"An ion is an atom or group of atoms with an electrical charge. If it loses electrons it becomes positive (a cation). If it gains electrons it becomes negative (an anion). Think: opposite charges attract."},
{keys:["lattice","lattice energy"],a:"A crystal lattice is an organized 3-D arrangement of ions. Lattice energy tells us how strongly those positive and negative ions hold onto each other. Bigger charges and smaller ion-to-ion distance usually mean stronger attraction."},
{keys:["covalent","covalent bond"],a:"A covalent bond is atoms sharing electrons. Instead of one atom fully giving an electron to another, the atoms share electron density between them."},
{keys:["metallic","metal"],a:"Metal atoms share a mobile 'sea' of electrons. Because those electrons can move, metals conduct electricity and heat well."},
{keys:["sigma","sigma bond"],a:"A sigma (σ) bond is the first bond between two atoms. The orbitals overlap head-on. Every single bond is one sigma bond."},
{keys:["pi","pi bond"],a:"A pi (π) bond is an extra bond formed by sideways orbital overlap. A double bond has one sigma plus one pi; a triple has one sigma plus two pi bonds."},
{keys:["bond order"],a:"Bond order is a simple way to count how many bonds connect two atoms: single = 1, double = 2, triple = 3. Higher bond order usually means a shorter, stronger bond."},
{keys:["potential energy","energy curve","bond length"],a:"Imagine two atoms approaching. Far apart, they barely interact. Closer, attraction lowers energy. At the best distance the energy is lowest—that is the equilibrium bond length. Push them too close and repulsion shoots up."},
{keys:["dissociation","dissociate"],a:"Dissociation means an ionic compound separates into its ions in water. NaCl becomes Na⁺ and Cl⁻. Those mobile charged particles are why the solution can conduct electricity."},
{keys:["conduct","conductivity","electricity"],a:"To conduct electricity, charged particles must be able to move. Metals have mobile electrons. Salt water has mobile ions. In solid salt the ions are charged but locked in place, so it conducts poorly."},
{keys:["lewis","lewis structure","valence"],a:"A Lewis structure is an electron bookkeeping picture. Start by counting valence electrons, connect the atoms, fill outer atoms' octets, then check the central atom and the total electron count."},
{keys:["octet"],a:"The octet rule is the useful idea that many main-group atoms become more stable with 8 electrons around them. It is a rule of thumb, not an absolute law—there are important exceptions."},
{keys:["resonance"],a:"Resonance means one Lewis drawing is not enough to show where electrons really are. We draw multiple valid electron arrangements; the real molecule is a blend, called a resonance hybrid."},
{keys:["formal charge"],a:"Formal charge is a bookkeeping tool for comparing Lewis structures: valence electrons − nonbonding electrons − half the bonding electrons. Usually we prefer reasonable structures with smaller formal charges."},
{keys:["vsepr","geometry","shape","lone pair"],a:"VSEPR says electron groups repel each other and spread out as much as possible. Count bonds around the central atom as electron domains (single/double/triple each count as one) and count lone pairs too. Those domains determine the 3-D shape."},
{keys:["tetrahedral"],a:"Tetrahedral means four electron domains spread into 3-D space, about 109.5° apart. CH₄ is the classic example."},
{keys:["trigonal pyramidal"],a:"Trigonal pyramidal usually means four electron domains: three bonds plus one lone pair, AX₃E. NH₃ is the classic example."},
{keys:["bent"],a:"Bent describes a molecule where the bonded atoms form an angle instead of a straight line. H₂O is bent because oxygen has two bonds and two lone pairs."}
];
HELP.push({keys:["intermolecular","dispersion","hydrogen bond","dipole"],a:"Intermolecular forces are attractions between separate molecules. All particles have dispersion forces; polar molecules can have dipole attractions; H bonded to N, O, or F can create hydrogen bonding."},{keys:["phase","solid","liquid","gas","boiling","melting"],a:"States of matter differ mostly in how particles move and how close they are. Solids are organized, liquids stay close but flow, and gases spread far apart. Phase changes involve changing particle attractions."},{keys:["ideal gas","pv=nrt","pressure","volume","kelvin"],a:"For gases, pressure comes from particles hitting container walls. PV=nRT connects pressure, volume, amount, and kelvin temperature. Smaller volume usually means higher pressure if the other conditions stay fixed."},{keys:["solution","solute","solvent","solubility"],a:"A solution is a uniform mixture. The solvent does the dissolving; the solute gets dissolved. A helpful first rule is like dissolves like: polar with polar, nonpolar with nonpolar."},{keys:["stoichiometry","balanced equation","coefficient","mole ratio"],a:"Stoichiometry treats a balanced chemical equation like a recipe. Balance with coefficients, then use those coefficients as mole ratios to calculate amounts."});const SIMPLE=[
"Ionic bonding: positive and negative ions attract like opposite magnetic poles. Stronger charges and shorter distance mean stronger attraction.",
"Metallic vs covalent: metals have mobile shared electrons; covalent bonds hold specific atoms together by sharing electrons.",
"Bond order: single, double, triple means 1, 2, 3. More bonding generally makes the bond shorter and stronger.",
"Potential energy: atoms have a 'just right' distance where the bond is most stable—not too far and not too close.",
"Conductivity: ask whether charged particles exist and whether they are free to move.",
"Lewis structures are electron bookkeeping drawings. Count electrons first, then make sure you used the right total.",
"Resonance means electrons are spread out in a way one Lewis drawing cannot fully show.",
"VSEPR predicts 3-D shape by letting electron groups spread apart to reduce repulsion."
];
function helperReply(q){let s=q.toLowerCase().trim();if(!s)return "Ask me a chemistry question, even if it feels basic.";let hit=HELP.find(x=>x.keys.some(k=>s.includes(k)));if(hit)return hit.a;if(s.includes("charge")&&s.includes("distance"))return "For ionic attraction, charge strengthens the pull and distance weakens it. Try Lattice Lab: increase charge, then move the ions farther apart and watch the relative attraction number.";return "That is a good question. I can currently help with the concepts in this unit: ions, lattice energy, metallic/covalent bonding, sigma and pi bonds, bond order, potential energy, conductivity, Lewis structures, resonance, formal charge, octets, and VSEPR. Try asking with one of those terms."}
function addHelp(text,who="bot"){let d=document.createElement("div");d.className="msg "+who;d.textContent=text;$("#helperChat").append(d);$("#helperChat").scrollTop=$("#helperChat").scrollHeight}
function initHelper(){let launch=$("#helperLaunch"),box=$("#helper"),close=$("#helperClose"),form=$("#helperForm"),input=$("#helperInput");if(!launch||!box)return;launch.onclick=()=>{box.hidden=false;if(!$("#helperChat").children.length)addHelp("Hi! I’m Atom. Ask me anything about what you’re learning. I’ll keep it simple.");input.focus()};close.onclick=()=>box.hidden=true;form.onsubmit=e=>{e.preventDefault();let q=input.value.trim();if(!q)return;addHelp(q,"student");addHelp(helperReply(q));input.value=""};document.querySelectorAll("[data-help]").forEach(b=>b.onclick=()=>{let type=b.dataset.help;if(type==="simple")addHelp(SIMPLE[cur]||"Focus on the main idea first, then use the example and simulator.");if(type==="example")addHelp(["NaCl is a simple ionic example: Na⁺ attracts Cl⁻.","Copper is metallic: mobile electrons help it conduct.","C=C is a double bond: 1σ + 1π.","Think of two magnets: there is a stable spacing, but pushing particles too close creates strong repulsion.","Salt water conducts because Na⁺ and Cl⁻ can move.","CO₂: count 16 valence electrons, then build O=C=O.","Ozone is a classic resonance example: one Lewis drawing alone is incomplete.","H₂O has four electron domains around O—two bonds and two lone pairs—so its molecular shape is bent."][cur]||"Try the lesson example.");if(type==="word")addHelp("Tell me the exact chemistry word that is confusing—for example: ion, lattice energy, sigma bond, resonance, formal charge, or VSEPR.");if(type==="why")addHelp("This matters because AP Chemistry questions often ask you to explain a property from particle-level structure—not just memorize a definition.")})}
initHelper();